import { ROCK_WIDTH_VW_LIMITS } from "../lib/rockScale.mjs";
import {
  DEFAULT_GLOW_OPTIMIZATION_SETTINGS,
  GLOW_OPTIMIZATION_LIMITS,
  GLOW_TARGET_FPS_VALUES,
} from "../lib/glowOptimization.mjs";
import { MIX_BLEND_MODES } from "../lib/settingsModel.mjs";
import "../../shared/room-settings.js";

const SharedRoomSettings = globalThis.SisyphusRoomSettings;
const DEFAULT_ROOM_SETTINGS = SharedRoomSettings.DEFAULT_ROOM_SETTINGS;

export const SETTINGS_STORAGE_KEY = "sisyphus-czar-settings-v40";
export const SETTINGS_VERSIONS_STORAGE_KEY = "sisyphus-czar-settings-versions-v1";
export const SETTINGS_SCENES = Object.freeze({
  CATS_AND_MICE: "cats-and-mice",
  TURNIP: "turnip",
});
export const SETTINGS_SCENE_OPTIONS = Object.freeze([
  Object.freeze({
    id: SETTINGS_SCENES.CATS_AND_MICE,
    label: "Сцена 1. Кошки-мышки",
  }),
  Object.freeze({
    id: SETTINGS_SCENES.TURNIP,
    label: "Сцена 2. Репка",
  }),
]);
export const LEGACY_SETTINGS_STORAGE_KEYS = [
  "sisyphus-czar-settings-v39",
  "sisyphus-czar-settings-v38",
  "sisyphus-czar-settings-v37",
  "sisyphus-czar-settings-v36",
  "sisyphus-czar-settings-v35",
  "sisyphus-czar-settings-v34",
  "sisyphus-czar-settings-v33",
  "sisyphus-czar-settings-v32",
  "sisyphus-czar-settings-v31",
  "sisyphus-czar-settings-v30",
  "sisyphus-czar-settings-v29",
  "sisyphus-czar-settings-v28",
  "sisyphus-czar-settings-v27",
  "sisyphus-czar-settings-v26",
  "sisyphus-czar-settings-v25",
  "sisyphus-czar-settings-v24",
  "sisyphus-czar-settings-v23",
  "sisyphus-czar-settings-v22",
  "sisyphus-czar-settings-v21",
  "sisyphus-czar-settings-v20",
  "sisyphus-czar-settings-v19",
  "sisyphus-czar-settings-v18",
  "sisyphus-czar-settings-v17",
  "sisyphus-czar-settings-v16",
  "sisyphus-czar-settings-v15",
  "sisyphus-czar-settings-v14",
  "sisyphus-czar-settings-v13",
  "sisyphus-czar-settings-v12",
  "sisyphus-czar-settings-v11",
  "sisyphus-czar-settings-v10",
  "sisyphus-czar-settings-v9",
  "sisyphus-czar-settings-v8",
  "sisyphus-czar-settings-v7",
  "sisyphus-czar-settings-v6",
  "sisyphus-czar-settings-v5",
  "sisyphus-czar-settings-v3",
  "sisyphus-czar-settings-v2",
];

const MIX_BLEND_LABELS = {
  normal: "Обычное",
  multiply: "Затемнение",
  screen: "Осветление",
  overlay: "Перекрытие",
  darken: "Темнее",
  lighten: "Светлее",
  "color-dodge": "Осветление основы",
  "color-burn": "Затемнение основы",
  "hard-light": "Жёсткий свет",
  "soft-light": "Мягкий свет",
  difference: "Негатив",
  exclusion: "Исключение",
};

const RAIN_MIX_BLEND_OPTIONS = MIX_BLEND_MODES.map((value) => [
  value,
  MIX_BLEND_LABELS[value],
]);

const ROCK_IMAGE_LABELS = Object.freeze({
  "rock-03": "rock-03.png",
  rock: "rock.webp",
  rock2: "rock2.png",
});
const ROCK_IMAGE_OPTIONS = SharedRoomSettings.ROCK_IMAGE_IDS.map((value) => [
  value,
  ROCK_IMAGE_LABELS[value],
]);

const PHYSICS_FORMULAS = {
  mass: [
    "F_g = m \\cdot g",
    "a_g = \\frac{F_g}{m}",
    "a_{hand} = \\frac{F_{hand}}{m}",
    "F_{surplus} = F_{hand} - F_g",
    "v_{x,release} = v_{x,pointer} \\cdot a_{hand} \\cdot p \\cdot \\frac{I_x}{1000} \\cdot k",
    "v_{y,release} = v_{y,pointer} \\cdot a_{hand} \\cdot p \\cdot \\frac{I_y}{10} \\cdot k",
    "t_{hold} = clamp\\left(\\frac{3000 \\cdot F_{hand}}{5 \\cdot F_g}, 500, 3000\\right)",
    "r = clamp\\left(\\frac{F_{hand}}{F_g}, 0, 1\\right)",
    "q = bezier(r)",
    "\\alpha(\\Delta t) = 1 - (1-q)^{\\Delta t / (1/60)}",
    "P_{rock}' = P_{rock} + \\alpha(\\Delta t)(P_{hand}-P_{rock})",
  ],
  gravity: [
    "F_g = m \\cdot g",
    "a_g = \\frac{F_g}{m} = g",
    "F_f = \\mu \\cdot F_g",
    "a_f = \\frac{F_f}{m}",
    "v_y' = v_y + a_g \\cdot \\Delta t",
  ],
  handForce: [
    "a_{hand} = \\frac{F_{hand}}{m}",
    "F_{surplus} = F_{hand} - F_g",
    "v_{x,release} = v_{x,pointer} \\cdot a_{hand} \\cdot p \\cdot \\frac{I_x}{1000} \\cdot k",
    "v_{y,release} = v_{y,pointer} \\cdot a_{hand} \\cdot p \\cdot \\frac{I_y}{10} \\cdot k",
    "t_{hold} = clamp\\left(\\frac{3000 \\cdot F_{hand}}{5 \\cdot F_g}, 500, 3000\\right)",
    "r = clamp\\left(\\frac{F_{hand}}{F_g}, 0, 1\\right)",
    "q = bezier(r)",
    "\\alpha(\\Delta t) = 1 - (1-q)^{\\Delta t / (1/60)}",
  ],
  handForceDeficitEasing: [
    "r = clamp\\left(\\frac{F_{hand}}{F_g}, 0, 1\\right)",
    "q = bezier(r)",
    "\\alpha(\\Delta t) = 1 - (1-q)^{\\Delta t / (1/60)}",
    "P_{rock}' = P_{rock} + \\alpha(\\Delta t)(P_{hand}-P_{rock})",
  ],
  pointerInfluence: [
    "v_{x,release} = v_{x,pointer} \\cdot \\frac{F_{hand}}{m} \\cdot p \\cdot \\frac{I_x}{1000} \\cdot k",
    "v_{y,release} = v_{y,pointer} \\cdot \\frac{F_{hand}}{m} \\cdot p \\cdot \\frac{I_y}{10} \\cdot k",
  ],
  bounce: [
    "v_y' = -min(v_y, v_{impactMax}) \\cdot b",
  ],
  inertia: [
    "I_y = \\frac{inertia}{10}",
    "v_{y,release}^{up} = v_{y,pointer} \\cdot \\frac{F_{hand}}{m} \\cdot p \\cdot I_y^2 \\cdot k",
    "v_{y,release}^{down} = v_{y,pointer} \\cdot \\frac{F_{hand}}{m} \\cdot p \\cdot I_y \\cdot k",
  ],
  horizontalInertia: [
    "I_x = \\frac{horizontalInertia}{1000}",
    "v_{x,release} = v_{x,pointer} \\cdot \\frac{F_{hand}}{m} \\cdot p \\cdot I_x \\cdot k",
  ],
  groundFriction: [
    "r_f(\\Delta t) = e^{-k_f \\cdot \\mu \\cdot \\Delta t}",
    "v_x' = 0, \\; \\mu = 1",
    "v_x' = v_x \\cdot r_f(\\Delta t), \\; 0 < \\mu < 1",
    "k_f = 5 \\; s^{-1}",
  ],
  turbulence: [
    "v_x' = v_x + T \\cdot (sin(5.3t) + 0.6sin(11.7t + 1.3)) \\cdot \\Delta t",
  ],
  rockScaleEasing: [
    "h = 1 - \\frac{y}{y_{max}}",
    "s = bezier(h)",
    "w = w_{min} + (w_{max} - w_{min}) \\cdot s",
  ],
  rockMinWidthVw: [
    "w = w_{min} + (w_{max} - w_{min}) \\cdot bezier(h)",
  ],
  rockMaxWidthVw: [
    "w = w_{min} + (w_{max} - w_{min}) \\cdot bezier(h)",
  ],
  rockJumpIntervalSeconds: [
    "t_{jump} = rockJumpIntervalSeconds",
  ],
  rockJumpAngleSpreadDegrees: [
    "A = rockJumpAngleSpreadDegrees",
    "\\theta = random\\left(-\\frac{A}{2}, \\frac{A}{2}\\right)",
  ],
  rockJumpInertiaSpreadPercent: [
    "S = \\frac{rockJumpInertiaSpreadPercent}{100}",
    "J_0 = F_{hand} \\cdot t_{impulse} \\cdot I_y",
    "J = J_0 \\cdot random(1-S, 1+S)",
    "V = clamp\\left(\\frac{J}{m}, V_{min}, V_{max}\\right)",
    "v_x = V \\cdot sin(\\theta)",
    "v_y = -V \\cdot cos(\\theta), \\quad \\theta \\in \\left[-\\frac{A}{2},\\frac{A}{2}\\right]",
  ],
  sceneHeightScreens: [
    "H_{page} = sceneHeightScreens \\cdot 100vh",
    "k_{scene} = \\frac{100}{sceneHeightScreens} \\cdot 10",
    "a_y' = a_y \\cdot k_{scene}",
  ],
  handWidthVw: [
    "w_{hand} = viewportWidth \\cdot \\frac{handWidthVw}{100}",
  ],
};

const TRAIL_STYLE_CONTROLS = [
  {
    name: "blendMode",
    label: "Смешивание",
    type: "select",
    defaultValue: DEFAULT_ROOM_SETTINGS.blendMode,
    options: [
      ["difference", "Негатив"],
      ["normal", "Обычное"],
      ["exclusion", "Исключение"],
      ["screen", "Осветление"],
      ["multiply", "Затемнение"],
    ],
    enabledWhen: { name: "themeMode", values: ["auto", "light"] },
    hint: "Как траектория накладывается на светлый фон. В фиксированной тёмной теме движок использует normal, поэтому поле отключено.",
  },
  {
    name: "lineColor",
    label: "Цвет линии",
    type: "color",
    defaultValue: DEFAULT_ROOM_SETTINGS.lineColor,
    hint: "Основной цвет траектории. При режиме «Негатив» чистый эффект даёт белый.",
  },
  {
    name: "lineColorTail",
    label: "Цвет хвоста",
    type: "color",
    defaultValue: DEFAULT_ROOM_SETTINGS.lineColorTail,
    enabledWhen: "useGradient",
    hint: "Цвет дальнего конца траектории. Доступен, когда включён градиент.",
  },
  {
    name: "useGradient",
    label: "Градиент к хвосту",
    type: "checkbox",
    defaultChecked: DEFAULT_ROOM_SETTINGS.useGradient,
    hint: "Плавный переход цвета от начала траектории к хвосту.",
  },
  {
    name: "lineOpacity",
    label: "Общая непрозрачность",
    type: "range",
    min: 0,
    max: 1,
    step: 0.05,
    defaultValue: DEFAULT_ROOM_SETTINGS.lineOpacity,
    output: DEFAULT_ROOM_SETTINGS.lineOpacity.toFixed(2),
    hint: "Прозрачность всего слоя траектории после накопления проходов.",
  },
  {
    name: "linePassOpacity",
    label: "Непрозрачность линии",
    type: "range",
    min: 0,
    max: 1,
    step: 0.05,
    defaultValue: DEFAULT_ROOM_SETTINGS.linePassOpacity,
    output: DEFAULT_ROOM_SETTINGS.linePassOpacity.toFixed(2),
    hint: "Вклад одного прохода линии. Повторные проходы по одному месту складываются до полной непрозрачности.",
  },
  {
    name: "dashStyle",
    label: "Стиль линии",
    type: "select",
    defaultValue: DEFAULT_ROOM_SETTINGS.dashStyle,
    options: [
      ["solid", "Сплошная"],
      ["dashed", "Пунктир"],
      ["dotted", "Точечная"],
    ],
    hint: "Сплошная линия, пунктир или точечный штрих.",
  },
  {
    name: "dashLength",
    label: "Длина штриха",
    type: "range",
    min: 1,
    max: 40,
    step: 1,
    defaultValue: DEFAULT_ROOM_SETTINGS.dashLength,
    output: String(DEFAULT_ROOM_SETTINGS.dashLength),
    enabledWhen: { name: "dashStyle", values: ["dashed"] },
    hint: "Длина чёрточки. Доступна только для пунктирного стиля.",
  },
  {
    name: "dashGap",
    label: "Промежуток",
    type: "range",
    min: 0,
    max: 40,
    step: 1,
    defaultValue: DEFAULT_ROOM_SETTINGS.dashGap,
    output: String(DEFAULT_ROOM_SETTINGS.dashGap),
    enabledWhen: { name: "dashStyle", values: ["dashed", "dotted"] },
    hint: "Пустое расстояние между штрихами. Доступно для пунктира и точечной линии.",
  },
  {
    name: "lineCap",
    label: "Концы линии",
    type: "select",
    defaultValue: DEFAULT_ROOM_SETTINGS.lineCap,
    options: [
      ["round", "Скругление"],
      ["butt", "Срез"],
      ["square", "Квадрат"],
    ],
    hint: "Форма кончиков линии: срез, скругление или квадрат.",
  },
  {
    name: "lineJoin",
    label: "Стыки",
    type: "select",
    defaultValue: DEFAULT_ROOM_SETTINGS.lineJoin,
    options: [
      ["round", "Скругление"],
      ["miter", "Острые"],
      ["bevel", "Фаска"],
    ],
    hint: "Как выглядят изломы линии на поворотах: острые углы, скругление или срезанная фаска.",
  },
  {
    name: "glow",
    label: "Свечение",
    type: "range",
    min: 0,
    max: 40,
    step: 1,
    defaultValue: DEFAULT_ROOM_SETTINGS.glow,
    output: String(DEFAULT_ROOM_SETTINGS.glow),
    hint: "Мягкое размытое сияние вокруг линии. Ноль — без сияния.",
  },
  {
    name: "glowColor",
    label: "Цвет свечения",
    type: "color",
    defaultValue: DEFAULT_ROOM_SETTINGS.glowColor,
    hint: "Цвет мягкого сияния вокруг линии.",
  },
  {
    name: "glowOptimizationMode",
    label: "Оптимизация свечения",
    type: "select",
    defaultValue: DEFAULT_GLOW_OPTIMIZATION_SETTINGS.glowOptimizationMode,
    options: [
      ["auto", "Авто"],
      ["performance", "Производительность"],
      ["balanced", "Баланс"],
      ["quality", "Качество"],
      ["manual", "Ручной"],
    ],
    scope: "local",
    hint: "Локальный профиль стоимости glow-слоя. Не синхронизируется с другими устройствами.",
  },
  {
    name: "glowTargetFps",
    label: "Целевой FPS",
    type: "select",
    defaultValue: DEFAULT_GLOW_OPTIMIZATION_SETTINGS.glowTargetFps,
    options: GLOW_TARGET_FPS_VALUES.map((value) => [String(value), String(value)]),
    enabledWhen: { name: "glowOptimizationMode", values: ["auto"] },
    scope: "local",
    hint: "Целевая частота всей сцены для автоматической адаптации. Доступна только в режиме «Авто».",
  },
  {
    name: "glowBufferScalePercent",
    label: "Масштаб glow-буфера",
    type: "range",
    min: GLOW_OPTIMIZATION_LIMITS.glowBufferScalePercent[0],
    max: GLOW_OPTIMIZATION_LIMITS.glowBufferScalePercent[1],
    step: 5,
    defaultValue: DEFAULT_GLOW_OPTIMIZATION_SETTINGS.glowBufferScalePercent,
    output: `${DEFAULT_GLOW_OPTIMIZATION_SETTINGS.glowBufferScalePercent}%`,
    enabledWhen: { name: "glowOptimizationMode", values: ["manual"] },
    scope: "local",
    hint: "Разрешение отдельного glow-canvas. Доступно только в ручном режиме.",
  },
  {
    name: "glowUpdateFps",
    label: "FPS свечения",
    type: "range",
    min: GLOW_OPTIMIZATION_LIMITS.glowUpdateFps[0],
    max: GLOW_OPTIMIZATION_LIMITS.glowUpdateFps[1],
    step: 1,
    defaultValue: DEFAULT_GLOW_OPTIMIZATION_SETTINGS.glowUpdateFps,
    output: String(DEFAULT_GLOW_OPTIMIZATION_SETTINGS.glowUpdateFps),
    enabledWhen: { name: "glowOptimizationMode", values: ["manual"] },
    scope: "local",
    hint: "Максимальная частота обновления glow-слоя. Доступна только в ручном режиме.",
  },
  {
    name: "glowMaxPoints",
    label: "Точек свечения",
    type: "range",
    min: GLOW_OPTIMIZATION_LIMITS.glowMaxPoints[0],
    max: GLOW_OPTIMIZATION_LIMITS.glowMaxPoints[1],
    step: 50,
    defaultValue: DEFAULT_GLOW_OPTIMIZATION_SETTINGS.glowMaxPoints,
    output: String(DEFAULT_GLOW_OPTIMIZATION_SETTINGS.glowMaxPoints),
    enabledWhen: { name: "glowOptimizationMode", values: ["manual"] },
    scope: "local",
    hint: "Жёсткий лимит точек только для glow-слоя. Доступен только в ручном режиме.",
  },
  {
    name: "glowDecimation",
    label: "Прореживание свечения",
    type: "range",
    min: GLOW_OPTIMIZATION_LIMITS.glowDecimation[0],
    max: GLOW_OPTIMIZATION_LIMITS.glowDecimation[1],
    step: 1,
    defaultValue: DEFAULT_GLOW_OPTIMIZATION_SETTINGS.glowDecimation,
    output: String(DEFAULT_GLOW_OPTIMIZATION_SETTINGS.glowDecimation),
    enabledWhen: { name: "glowOptimizationMode", values: ["manual"] },
    scope: "local",
    hint: "Минимальный шаг выборки точек glow-пути. Доступен только в ручном режиме.",
  },
];

export function settingsGroupControls(group) {
  return [
    ...(Array.isArray(group.controls) ? group.controls : []),
    ...(Array.isArray(group.subgroups)
      ? group.subgroups.flatMap(settingsGroupControls)
      : []),
  ];
}

const CATS_AND_MICE_ONLY_SETTING_NAMES = new Set([
  "preclickHopGuardClickCount",
  "preclickHopActivationRadiusPercent",
  "preclickHopMaxDistancePercent",
]);

const TRAIL_SCENE_SETTING_NAMES = [
  "trailEnabled",
  "trailAnchorHeightPercent",
  "lineDelay",
  "lineWidth",
  "trailReset",
  "trailMaxPoints",
  "trailUnlimited",
  "trailSampleDist",
  ...TRAIL_STYLE_CONTROLS.map((control) => control.name),
];

const SHARED_SCENE_SETTING_NAMES = new Set([
  "themeMode",
  "lightBackgroundColor",
  "lightBackgroundDeepColor",
  "lightBackgroundLowColor",
  "darkBackgroundColor",
  "darkBackgroundDeepColor",
  "darkBackgroundLowColor",
  "sceneHeightScreens",
  "foldPositionPercent",
  "foldPanelHeightVh",
  "foldAngle",
  "foldZoneSize",
  "foldBlendEnabled",
  "foldBlendCurve",
  "rockImageId",
  "foldRockImageId",
  "rockPulseEnabled",
  "rockPulseShrinkPercent",
  "rockPulseBpm",
  "rockMinWidthVw",
  "rockMaxWidthVw",
  "customCursorEnabled",
  "customCursorSizePx",
  "handVisibilityMode",
  "handImageChangeDelayMs",
  "rockGrabRadiusVh",
  "handAudioEnabled",
  "handWidthVw",
  ...TRAIL_SCENE_SETTING_NAMES,
]);

const CATS_AND_MICE_SCENES = Object.freeze([
  SETTINGS_SCENES.CATS_AND_MICE,
]);
const TURNIP_SCENES = Object.freeze([SETTINGS_SCENES.TURNIP]);
const SHARED_SCENES = Object.freeze([
  SETTINGS_SCENES.CATS_AND_MICE,
  SETTINGS_SCENES.TURNIP,
]);

export function settingsControlScenes(control) {
  const name = typeof control === "string" ? control : control?.name;
  if (CATS_AND_MICE_ONLY_SETTING_NAMES.has(name)) {
    return CATS_AND_MICE_SCENES;
  }
  if (SHARED_SCENE_SETTING_NAMES.has(name)) {
    return SHARED_SCENES;
  }
  return TURNIP_SCENES;
}

export function settingsControlVisibleInScene(control, sceneId) {
  return settingsControlScenes(control).includes(sceneId);
}

export function settingsGroupVisibleInScene(group, sceneId) {
  return settingsGroupControls(group).some((control) =>
    settingsControlVisibleInScene(control, sceneId),
  );
}

export const SETTINGS_GROUPS = [
  {
    title: "Вид",
    controls: [
      {
        name: "themeMode",
        label: "Тема",
        type: "select",
        defaultValue: DEFAULT_ROOM_SETTINGS.themeMode,
        options: [
          ["auto", "Авто"],
          ["dark", "Тёмная"],
          ["light", "Светлая"],
        ],
        hint: "Авто сохраняет текущую механику: светлая тема включается в верхнем отпечатке. Ручные режимы фиксируют выбранную тему локально.",
      },
      {
        name: "lightBackgroundColor",
        label: "Светлый фон: верх",
        type: "color",
        defaultValue: DEFAULT_ROOM_SETTINGS.lightBackgroundColor,
        hint: "Базовый верхний цвет градиента светлой темы, точка 0%.",
      },
      {
        name: "lightBackgroundDeepColor",
        label: "Светлый фон: середина",
        type: "color",
        defaultValue: DEFAULT_ROOM_SETTINGS.lightBackgroundDeepColor,
        hint: "Промежуточный цвет градиента светлой темы, точка 48%.",
      },
      {
        name: "lightBackgroundLowColor",
        label: "Светлый фон: низ",
        type: "color",
        defaultValue: DEFAULT_ROOM_SETTINGS.lightBackgroundLowColor,
        hint: "Нижний цвет градиента светлой темы, точка 100%.",
      },
      {
        name: "darkBackgroundColor",
        label: "Тёмный фон: верх",
        type: "color",
        defaultValue: DEFAULT_ROOM_SETTINGS.darkBackgroundColor,
        hint: "Базовый верхний цвет градиента тёмной темы, точка 0%.",
      },
      {
        name: "darkBackgroundDeepColor",
        label: "Тёмный фон: середина",
        type: "color",
        defaultValue: DEFAULT_ROOM_SETTINGS.darkBackgroundDeepColor,
        hint: "Промежуточный цвет градиента тёмной темы, точка 48%.",
      },
      {
        name: "darkBackgroundLowColor",
        label: "Тёмный фон: низ",
        type: "color",
        defaultValue: DEFAULT_ROOM_SETTINGS.darkBackgroundLowColor,
        hint: "Нижний цвет градиента тёмной темы, точка 100%.",
      },
      {
        name: "sceneHeightScreens",
        label: "Высота страницы",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.sceneHeightScreens[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.sceneHeightScreens[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.sceneHeightScreens,
        output: `${DEFAULT_ROOM_SETTINGS.sceneHeightScreens * 100}vh`,
        hint: "Общая высота сцены в экранах. При изменении автоматически применяется внутренний коэффициент скорости относительно старой длинной сцены 10000vh.",
        formulas: PHYSICS_FORMULAS.sceneHeightScreens,
      },
    ],
  },
  {
    title: "Камера",
    controls: [
      {
        name: "cameraFollowLerp",
        label: "Lerp камеры",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.cameraFollowLerp[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.cameraFollowLerp[1],
        step: 0.01,
        defaultValue: DEFAULT_ROOM_SETTINGS.cameraFollowLerp,
        output: DEFAULT_ROOM_SETTINGS.cameraFollowLerp.toFixed(2),
        hint: "После первого клика камера удерживает центр камня на середине viewport. Единица перемещает камеру к цели сразу, меньшие значения делают следование плавнее.",
      },
    ],
  },
  {
    title: "3D Fold",
    controls: [
      {
        name: "foldPositionPercent",
        label: "Положение на странице",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.foldPositionPercent[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.foldPositionPercent[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.foldPositionPercent,
        output: `${DEFAULT_ROOM_SETTINGS.foldPositionPercent}%`,
        hint: "Вертикальное положение Fold относительно полной высоты сцены: 0% — верх, 100% — самое нижнее положение без выхода за границу.",
      },
      {
        name: "foldPanelHeightVh",
        label: "Высота панели",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.foldPanelHeightVh[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.foldPanelHeightVh[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.foldPanelHeightVh,
        output: `${DEFAULT_ROOM_SETTINGS.foldPanelHeightVh} vh`,
        hint: "Высота видимой Fold-панели относительно viewport. Не изменяет внутренний размер перспективной линзы.",
      },
      {
        name: "foldAngle",
        label: "Угол линзы",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.foldAngle[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.foldAngle[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.foldAngle,
        output: `${DEFAULT_ROOM_SETTINGS.foldAngle}°`,
        hint: "Угол наклона верхней перспективной Fold-зоны.",
      },
      {
        name: "foldZoneSize",
        label: "Размер линзы",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.foldZoneSize[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.foldZoneSize[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.foldZoneSize,
        output: `${DEFAULT_ROOM_SETTINGS.foldZoneSize} vh`,
        hint: "Высота верхней Fold-зоны. Нулевое значение отключает эффект.",
      },
      {
        name: "foldBlendEnabled",
        label: "Плавное смешивание",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.foldBlendEnabled,
        hint: "Смешивает Fold-зону с основной сценой по настраиваемой кривой.",
      },
      {
        name: "foldBlendCurve",
        label: "Кривая смешивания",
        type: "cubic-bezier",
        defaultValue: DEFAULT_ROOM_SETTINGS.foldBlendCurve,
        enabledWhen: "foldBlendEnabled",
        hint: "Кривая изменения непрозрачности от верхнего края Fold-зоны к основной сцене.",
      },
    ],
  },
  {
    title: "Финальное падение",
    controls: [
      {
        name: "finalFallEnabled",
        label: "Непрерывное падение с вершины",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.finalFallEnabled,
        hint: "После выдержки на вершине отпущенный камень переходит в финальное падение без повторной остановки на верхнем отпечатке.",
      },
      {
        name: "finalFallDelaySeconds",
        label: "Задержка активации",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.finalFallDelaySeconds[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.finalFallDelaySeconds[1],
        step: 0.1,
        defaultValue: DEFAULT_ROOM_SETTINGS.finalFallDelaySeconds,
        output: `${DEFAULT_ROOM_SETTINGS.finalFallDelaySeconds.toFixed(1)} s`,
        hint: "Сколько камень должен непрерывно находиться на вершине, прежде чем правило применится при последующем отпускании.",
      },
    ],
  },
  {
    title: "Физика",
    controls: [
      {
        name: "gravity",
        label: "Тяготение",
        type: "range",
        min: 0.1,
        max: 100,
        step: 0.05,
        defaultValue: 9.8,
        output: "9.80",
        hint: "Ускорение свободного падения g. По умолчанию близко к земному значению 9.8.",
        formulas: PHYSICS_FORMULAS.gravity,
      },
      {
        name: "bounce",
        label: "Пружинистость",
        type: "range",
        min: 0,
        max: 1,
        step: 0.01,
        defaultValue: 0.35,
        output: "0.35",
        hint: "Сила пружинистого подпрыгивания камня при ударе о низ. Ноль — без отскока, единица — максимальный отскок.",
        formulas: PHYSICS_FORMULAS.bounce,
      },
      {
        name: "inertia",
        label: "Вертикальная инерция",
        type: "range",
        min: 0,
        max: 5,
        step: 0.01,
        defaultValue: 0.9,
        output: "0.90",
        hint: "Коэффициент вертикального импульса при отпускании или авто-выпадении. В физике значение делится на 10: 1 на ползунке даёт 0.1 реального коэффициента.",
        formulas: PHYSICS_FORMULAS.inertia,
      },
      {
        name: "horizontalInertia",
        label: "Горизонтальная инерция",
        type: "range",
        min: 0,
        max: 5,
        step: 0.01,
        defaultValue: 0.02,
        output: "0.02",
        hint: "Отдельный коэффициент горизонтального импульса. В физике значение делится на 1000, чтобы камень не улетал в стороны.",
        formulas: PHYSICS_FORMULAS.horizontalInertia,
      },
      {
        name: "groundFriction",
        label: "Трение земли",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.35,
        output: "0.35",
        hint: "Сила трения на нижней земле. Ноль — без дополнительного торможения, промежуточные значения плавно гасят инерцию, единица полностью исключает проскальзывание.",
        formulas: PHYSICS_FORMULAS.groundFriction,
      },
      {
        name: "turbulence",
        label: "Турбулентность",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.4,
        output: "0.40",
        hint: "Сила воздушной турбулентности: камень рыскает в стороны, но вертикальная скорость от турбулентности не меняется. Ноль — без турбулентности.",
        formulas: PHYSICS_FORMULAS.turbulence,
      },
    ],
  },
  {
    title: "Камень",
    controls: [
      {
        name: "randomDropEnabled",
        label: "Случайное выпадение",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.randomDropEnabled,
        hint: "Разрешает существующее случайное выпадение камня из руки через 0,5–2 секунды. Выпрыгивание вверх настраивается отдельно.",
      },
      {
        name: "rockJumpEnabled",
        label: "Выпрыгивание вверх",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.rockJumpEnabled,
        hint: "Периодически освобождает камень из руки и задаёт ему случайный импульс в настраиваемом секторе вокруг вертикали вверх.",
      },
      {
        name: "rockJumpIntervalSeconds",
        label: "Интервал выпрыгивания",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .rockJumpIntervalSeconds[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .rockJumpIntervalSeconds[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockJumpIntervalSeconds,
        output: `${DEFAULT_ROOM_SETTINGS.rockJumpIntervalSeconds} s`,
        enabledWhen: "rockJumpEnabled",
        hint: "Сколько секунд непрерывного удержания проходит до автоматического выпрыгивания вверх.",
        formulas: PHYSICS_FORMULAS.rockJumpIntervalSeconds,
      },
      {
        name: "rockJumpAngleSpreadDegrees",
        label: "Разброс угла",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .rockJumpAngleSpreadDegrees[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .rockJumpAngleSpreadDegrees[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockJumpAngleSpreadDegrees,
        output: `${DEFAULT_ROOM_SETTINGS.rockJumpAngleSpreadDegrees}°`,
        enabledWhen: "rockJumpEnabled",
        hint: "Полная ширина сектора вокруг вертикали вверх. Ноль направляет камень строго вверх, 180° разрешает всю верхнюю полуплоскость.",
        formulas: PHYSICS_FORMULAS.rockJumpAngleSpreadDegrees,
      },
      {
        name: "rockJumpInertiaSpreadPercent",
        label: "Разброс силы",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .rockJumpInertiaSpreadPercent[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .rockJumpInertiaSpreadPercent[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockJumpInertiaSpreadPercent,
        output: `${DEFAULT_ROOM_SETTINGS.rockJumpInertiaSpreadPercent}%`,
        enabledWhen: "rockJumpEnabled",
        hint: "Симметричное случайное отклонение величины импульса относительно базового значения. Ноль сохраняет базовую силу без разброса.",
        formulas: PHYSICS_FORMULAS.rockJumpInertiaSpreadPercent,
      },
      {
        name: "mass",
        label: "Масса",
        type: "range",
        min: 0.1,
        max: 100,
        step: 0.1,
        defaultValue: 1,
        output: "1",
        hint: "Масса камня. Участвует в силе тяжести, ускорении от руки и передаче импульса.",
        formulas: PHYSICS_FORMULAS.mass,
      },
      {
        name: "rockImageId",
        label: "Изображение основного камня",
        type: "select",
        options: ROCK_IMAGE_OPTIONS,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockImageId,
        hint: "Изображение основного камня и его отпечатка. Fold-зеркало настраивается отдельно.",
      },
      {
        name: "foldRockImageId",
        label: "Изображение камня в fold-зеркале",
        type: "select",
        options: ROCK_IMAGE_OPTIONS,
        defaultValue: DEFAULT_ROOM_SETTINGS.foldRockImageId,
        hint: "Независимое изображение камня внутри верхнего fold-зеркала.",
      },
      {
        name: "rockScaleEasing",
        label: "Кривая размера",
        type: "cubic-bezier",
        defaultValue: DEFAULT_ROOM_SETTINGS.rockScaleEasing,
        spellCheck: false,
        hint: "cubic-bezier кривая масштаба камня от нижнего положения к верхнему. Невалидное значение заменяется стандартной кривой.",
        formulas: PHYSICS_FORMULAS.rockScaleEasing,
      },
      {
        name: "rockActivatedWidthVw",
        label: "Размер после запуска физики, %",
        type: "number",
        min: ROCK_WIDTH_VW_LIMITS[0],
        max: ROCK_WIDTH_VW_LIMITS[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockActivatedWidthVw,
        output: `${DEFAULT_ROOM_SETTINGS.rockActivatedWidthVw}%`,
        hint: "Целевая ширина камня в vw при первом свободном движении вниз после захвата. Переход длится 300 мс.",
      },
      {
        name: "rockPressShrinkPercent",
        label: "Уменьшение при нажатии, %",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .rockPressShrinkPercent[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .rockPressShrinkPercent[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockPressShrinkPercent,
        output: `${DEFAULT_ROOM_SETTINGS.rockPressShrinkPercent}%`,
        hint: "Временно уменьшает текущий размер камня на заданный процент при pointerdown. Ноль отключает эффект.",
      },
      {
        name: "rockWallPenetrationPercent",
        label: "Вход в нижнюю и боковые стены, %",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .rockWallPenetrationPercent[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .rockWallPenetrationPercent[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockWallPenetrationPercent,
        output: `${DEFAULT_ROOM_SETTINGS.rockWallPenetrationPercent}%`,
        hint: "Разрешает камню входить в нижнюю, левую и правую стены на заданную долю своего текущего визуального размера. Верхняя граница не изменяется.",
      },
      {
        name: "rockPulseEnabled",
        label: "Пульс камня",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.rockPulseEnabled,
        hint: "Включает ритмичное уменьшение и восстановление камня с отдельной глубиной пульса.",
      },
      {
        name: "rockPulseShrinkPercent",
        label: "Уменьшение при пульсе, %",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .rockPulseShrinkPercent[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .rockPulseShrinkPercent[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockPulseShrinkPercent,
        output: `${DEFAULT_ROOM_SETTINGS.rockPulseShrinkPercent}%`,
        enabledWhen: "rockPulseEnabled",
        hint: "Максимальное уменьшение камня в фазе сжатия пульса. Ноль оставляет пульс без изменения размера.",
      },
      {
        name: "rockPulseBpm",
        label: "Частота пульса, BPM",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.rockPulseBpm[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.rockPulseBpm[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockPulseBpm,
        output: `${DEFAULT_ROOM_SETTINGS.rockPulseBpm} BPM`,
        enabledWhen: "rockPulseEnabled",
        hint: "Количество ударов в минуту. 60 BPM — один полный пульс в секунду.",
      },
      {
        name: "preclickHopGuardClickCount",
        label: "Количество фейковых кликов",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .preclickHopGuardClickCount[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .preclickHopGuardClickCount[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.preclickHopGuardClickCount,
        output: `${DEFAULT_ROOM_SETTINGS.preclickHopGuardClickCount}`,
        hint: "Первые N кликов по камню вызывают только бесшумный фейковый отскок. Следующий клик включает физику и переводит игру в сцену «Репка»; ноль отключает фейковые клики.",
      },
      {
        name: "preclickHopActivationRadiusPercent",
        label: "Радиус срабатывания, % камня",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .preclickHopActivationRadiusPercent[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .preclickHopActivationRadiusPercent[1],
        step: 1,
        defaultValue:
          DEFAULT_ROOM_SETTINGS.preclickHopActivationRadiusPercent,
        output:
          `${DEFAULT_ROOM_SETTINGS.preclickHopActivationRadiusPercent}%`,
        hint: "Радиус круглой зоны вокруг текущего центра камня в процентах от его текущей визуальной ширины. Каждый новый вход курсора запускает один отскок; ноль отключает срабатывание.",
      },
      {
        name: "preclickHopMaxDistancePercent",
        label: "Максимальный отскок, %",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .preclickHopMaxDistancePercent[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .preclickHopMaxDistancePercent[1],
        step: 0.1,
        defaultValue: DEFAULT_ROOM_SETTINGS.preclickHopMaxDistancePercent,
        output:
          `${DEFAULT_ROOM_SETTINGS.preclickHopMaxDistancePercent.toFixed(1)}%`,
        hint: "Верхняя граница отскока относительно размера viewport по направлению движения. Скорость руки задаёт от 28% до 100%; небезопасная траектория сокращается или отклоняется от руки.",
      },
      {
        name: "rockMinWidthVw",
        label: "Начальный размер, %",
        type: "number",
        min: ROCK_WIDTH_VW_LIMITS[0],
        max: ROCK_WIDTH_VW_LIMITS[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockMinWidthVw,
        output: `${DEFAULT_ROOM_SETTINGS.rockMinWidthVw}%`,
        hint: "Ширина камня в начале пути, у нижней границы, в процентах от ширины экрана. Значение может быть больше конечного.",
        formulas: PHYSICS_FORMULAS.rockMinWidthVw,
      },
      {
        name: "rockMaxWidthVw",
        label: "Конечный размер, %",
        type: "number",
        min: ROCK_WIDTH_VW_LIMITS[0],
        max: ROCK_WIDTH_VW_LIMITS[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockMaxWidthVw,
        output: `${DEFAULT_ROOM_SETTINGS.rockMaxWidthVw}%`,
        hint: "Ширина камня в конце пути, у вершины, в процентах от ширины экрана. Значение может быть меньше начального.",
        formulas: PHYSICS_FORMULAS.rockMaxWidthVw,
      },
    ],
  },
  {
    title: "Курсор",
    controls: [
      {
        name: "customCursorEnabled",
        label: "Показывать курсор",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.customCursorEnabled,
        hint: "Показывает SVG-курсор из assets/cursor одновременно с фото-рукой для всех участников комнаты.",
      },
      {
        name: "customCursorSizePx",
        label: "Размер курсора, px",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.customCursorSizePx[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.customCursorSizePx[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.customCursorSizePx,
        output: `${DEFAULT_ROOM_SETTINGS.customCursorSizePx}px`,
        enabledWhen: "customCursorEnabled",
        hint: "Размер SVG-курсора в пикселях. Значение сохраняется, когда показ курсора выключен.",
      },
    ],
  },
  {
    title: "Рука",
    controls: [
      {
        name: "handVisibilityMode",
        label: "Отображение руки",
        type: "select",
        defaultValue: DEFAULT_ROOM_SETTINGS.handVisibilityMode,
        options: [
          ["always", "Показывать всегда"],
          ["hover", "Показывать по hover"],
          ["hidden", "Не показывать"],
        ],
        hint: "Рука может быть постоянной, появляться только над камнем или быть полностью скрыта.",
      },
      {
        name: "handImageChangeDelayMs",
        label: "Задержка смены изображения, мс",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.handImageChangeDelayMs[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.handImageChangeDelayMs[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.handImageChangeDelayMs,
        output: `${DEFAULT_ROOM_SETTINGS.handImageChangeDelayMs}мс`,
        hint: "Задержка между основным кликом и сменой изображения руки. Ноль переключает изображение сразу.",
      },
      {
        name: "rockGrabRadiusVh",
        label: "Радиус захвата камня, vh",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.rockGrabRadiusVh[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.rockGrabRadiusVh[1],
        step: 0.1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockGrabRadiusVh,
        output: `${DEFAULT_ROOM_SETTINGS.rockGrabRadiusVh.toFixed(1)}vh`,
        hint: "Расширяет mouse-захват вокруг визуальных границ камня. Ноль сохраняет захват только непосредственно по камню; touch не расширяется.",
      },
      {
        name: "handAudioEnabled",
        label: "Звуки руки",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.handAudioEnabled,
        hint: "Включает звуки наведения руки на камень и захвата камня.",
      },
      {
        name: "handForce",
        label: "Сила",
        type: "range",
        min: 1,
        max: 1000,
        step: 1,
        defaultValue: 50,
        output: "50",
        hint: "Сила единственной руки в сессии. При нехватке силы камень плавно отстаёт; отношение Fhand/Fg задаёт скорость следования.",
        formulas: PHYSICS_FORMULAS.handForce,
      },
      {
        name: "handForceDeficitEasing",
        label: "Кривая нехватки силы",
        type: "cubic-bezier",
        defaultValue: DEFAULT_ROOM_SETTINGS.handForceDeficitEasing,
        spellCheck: false,
        hint: "cubic-bezier кривая реакции камня, когда сила руки меньше силы тяжести. Невалидное значение заменяется последней корректной или стандартной кривой.",
        formulas: PHYSICS_FORMULAS.handForceDeficitEasing,
      },
      {
        name: "pointerInfluence",
        label: "Влияние рывка",
        type: "range",
        min: 0,
        max: 10,
        step: 0.1,
        defaultValue: 1,
        output: "1.0",
        hint: "Насколько скорость движения мыши влияет на силу броска. Ноль — рывок не учитывается.",
        formulas: PHYSICS_FORMULAS.pointerInfluence,
      },
      {
        name: "heightGates",
        label: "Высотные остановки",
        type: "height-gates",
        defaultValue: JSON.stringify(DEFAULT_ROOM_SETTINGS.heightGates),
        hint: "До 10 скрытых меток. Каждая один раз останавливает только подъём камня на своей высоте и разрешает продолжить путь после индивидуального таймера.",
      },
      {
        name: "handWidthVw",
        label: "Размер руки, vw",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.handWidthVw[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.handWidthVw[1],
        step: 0.125,
        defaultValue: DEFAULT_ROOM_SETTINGS.handWidthVw,
        output: `${DEFAULT_ROOM_SETTINGS.handWidthVw.toFixed(1)}vw`,
        hint: "Ширина единственной руки текущего пользователя в процентах от ширины экрана.",
        formulas: PHYSICS_FORMULAS.handWidthVw,
      },
    ],
  },
  {
    title: "Препятствия",
    controls: [],
    subgroups: [
      {
        title: "Окна",
        permissionControl: "window-obstacle",
        controls: [
          {
            name: "windowObstacleEnabled",
            label: "Включить окна",
            type: "checkbox",
            defaultChecked: DEFAULT_ROOM_SETTINGS.windowObstacleEnabled,
            hint: "Открывает пустые окна браузера, пока центр камня находится в настроенном диапазоне высоты.",
          },
          {
            name: "windowObstacleMinHeightVh",
            label: "Высота от",
            type: "number",
            min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleHeightVh[0],
            max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleHeightVh[1],
            step: 100,
            defaultValue: DEFAULT_ROOM_SETTINGS.windowObstacleMinHeightVh,
            output: `${DEFAULT_ROOM_SETTINGS.windowObstacleMinHeightVh}vh`,
            enabledWhen: "windowObstacleEnabled",
            hint: "Нижняя граница зоны от начала подъёма. Ноль соответствует нижней точке пути.",
          },
          {
            name: "windowObstacleMaxHeightVh",
            label: "Высота до",
            type: "number",
            min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleHeightVh[0],
            max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleHeightVh[1],
            step: 100,
            defaultValue: DEFAULT_ROOM_SETTINGS.windowObstacleMaxHeightVh,
            output: `${DEFAULT_ROOM_SETTINGS.windowObstacleMaxHeightVh}vh`,
            enabledWhen: "windowObstacleEnabled",
            hint: "Верхняя граница зоны, внутри которой планируются новые окна.",
          },
          {
            name: "windowObstacleMinIntervalSeconds",
            label: "Интервал от",
            type: "number",
            min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleIntervalSeconds[0],
            max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleIntervalSeconds[1],
            step: 0.1,
            defaultValue: DEFAULT_ROOM_SETTINGS.windowObstacleMinIntervalSeconds,
            output: `${DEFAULT_ROOM_SETTINGS.windowObstacleMinIntervalSeconds.toFixed(1)} s`,
            enabledWhen: "windowObstacleEnabled",
            hint: "Минимальное случайное ожидание перед следующим успешным показом.",
          },
          {
            name: "windowObstacleMaxIntervalSeconds",
            label: "Интервал до",
            type: "number",
            min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleIntervalSeconds[0],
            max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleIntervalSeconds[1],
            step: 0.1,
            defaultValue: DEFAULT_ROOM_SETTINGS.windowObstacleMaxIntervalSeconds,
            output: `${DEFAULT_ROOM_SETTINGS.windowObstacleMaxIntervalSeconds.toFixed(1)} s`,
            enabledWhen: "windowObstacleEnabled",
            hint: "Максимальное случайное ожидание перед следующим успешным показом.",
          },
          {
            name: "windowObstacleMinWidthPx",
            label: "Ширина от",
            type: "number",
            min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleWidthPx[0],
            max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleWidthPx[1],
            step: 10,
            defaultValue: DEFAULT_ROOM_SETTINGS.windowObstacleMinWidthPx,
            output: `${DEFAULT_ROOM_SETTINGS.windowObstacleMinWidthPx}px`,
            enabledWhen: "windowObstacleEnabled",
            hint: "Минимальная ширина нового окна с учётом доступной рабочей области экрана.",
          },
          {
            name: "windowObstacleMaxWidthPx",
            label: "Ширина до",
            type: "number",
            min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleWidthPx[0],
            max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleWidthPx[1],
            step: 10,
            defaultValue: DEFAULT_ROOM_SETTINGS.windowObstacleMaxWidthPx,
            output: `${DEFAULT_ROOM_SETTINGS.windowObstacleMaxWidthPx}px`,
            enabledWhen: "windowObstacleEnabled",
            hint: "Максимальная ширина нового окна с учётом доступной рабочей области экрана.",
          },
          {
            name: "windowObstacleMinHeightPx",
            label: "Высота окна от",
            type: "number",
            min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleHeightPx[0],
            max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleHeightPx[1],
            step: 10,
            defaultValue: DEFAULT_ROOM_SETTINGS.windowObstacleMinHeightPx,
            output: `${DEFAULT_ROOM_SETTINGS.windowObstacleMinHeightPx}px`,
            enabledWhen: "windowObstacleEnabled",
            hint: "Минимальная высота нового окна с учётом доступной рабочей области экрана.",
          },
          {
            name: "windowObstacleMaxHeightPx",
            label: "Высота окна до",
            type: "number",
            min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleHeightPx[0],
            max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.windowObstacleHeightPx[1],
            step: 10,
            defaultValue: DEFAULT_ROOM_SETTINGS.windowObstacleMaxHeightPx,
            output: `${DEFAULT_ROOM_SETTINGS.windowObstacleMaxHeightPx}px`,
            enabledWhen: "windowObstacleEnabled",
            hint: "Максимальная высота нового окна с учётом доступной рабочей области экрана.",
          },
        ],
      },
    ],
  },
  {
    title: "Траектория",
    controls: [
      {
        name: "trailEnabled",
        label: "Показывать траекторию",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.trailEnabled,
        hint: "Включает или выключает отрисовку траектории за камнем.",
      },
      {
        name: "trailAnchorHeightPercent",
        label: "Точка линии по высоте, %",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .trailAnchorHeightPercent[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .trailAnchorHeightPercent[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.trailAnchorHeightPercent,
        output: `${DEFAULT_ROOM_SETTINGS.trailAnchorHeightPercent.toFixed(
          0,
        )}%`,
        hint: "Вертикальная точка привязки траектории: 0% — верх изображения камня, 100% — центр нижней границы.",
      },
      {
        name: "lineDelay",
        label: "Задержка",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: DEFAULT_ROOM_SETTINGS.lineDelay,
        output: DEFAULT_ROOM_SETTINGS.lineDelay.toFixed(2),
        hint: "Насколько плавно и с какой задержкой линия догоняет камень. Ноль — линия точно повторяет путь; больше — линия мягко тянется за камнем с задержкой и сильнее сглаживается.",
      },
      {
        name: "lineWidth",
        label: "Толщина",
        type: "range",
        min: 1,
        max: 60,
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.lineWidth,
        output: String(DEFAULT_ROOM_SETTINGS.lineWidth),
        hint: "Толщина линии траектории. Больше значение — толще линия.",
      },
      {
        name: "trailReset",
        label: "Сбрасывать при касании земли",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.trailReset,
        hint: "Стирать траекторию каждый раз, когда камень касается нижней земли. Выключено — траектория копится.",
      },
      {
        name: "trailMaxPoints",
        label: "Длина траектории",
        type: "range",
        min: 20,
        max: 2000,
        step: 10,
        defaultValue: DEFAULT_ROOM_SETTINGS.trailMaxPoints,
        output: String(DEFAULT_ROOM_SETTINGS.trailMaxPoints),
        hint: "Сколько последних точек пути хранить. Больше — длиннее видимая траектория.",
      },
      {
        name: "trailUnlimited",
        label: "Без ограничения длины",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.trailUnlimited,
        hint: "Не удалять старые точки траектории и сохранять их после перезагрузки страницы. При долгой работе расход памяти и нагрузка на отрисовку будут расти.",
      },
      {
        name: "trailSampleDist",
        label: "Частота точек",
        type: "range",
        min: 1,
        max: 40,
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.trailSampleDist,
        output: String(DEFAULT_ROOM_SETTINGS.trailSampleDist),
        hint: "Как часто ставится новая точка траектории. Меньше значение — точки плотнее и линия глаже.",
      },
    ],
    subgroups: [
      {
        title: "Стиль",
        controls: TRAIL_STYLE_CONTROLS,
      },
    ],
    action: {
      className: "trail-clear",
      label: "Очистить траекторию",
      hint: "Стирает нарисованную траекторию прямо сейчас.",
    },
  },
  {
    title: "Дождь",
    controls: [
      {
        name: "rainEnabled",
        label: "Включить дождь",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.rainEnabled,
        hint: "Локально включает или выключает дождь по клику. Возврат камня в отпечаток всё равно временно включает ливень.",
      },
      {
        name: "rainStrength",
        label: "Сила дождя",
        type: "range",
        min: 0.25,
        max: 1.5,
        step: 0.05,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainStrength,
        output: `${Math.round(DEFAULT_ROOM_SETTINGS.rainStrength * 100)}%`,
        hint: "Плотность и заметность ливня. Больше значение — больше капель и сильнее дождевой эффект.",
      },
      {
        name: "rainMaxVolume",
        label: "Максимальная громкость",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.rainMaxVolume[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.rainMaxVolume[1],
        step: 0.01,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainMaxVolume,
        output: `${Math.round(DEFAULT_ROOM_SETTINGS.rainMaxVolume * 100)}%`,
        hint: "Целевая громкость звука дождя. Значения выше 100% усиливают сигнал через Web Audio.",
      },
      {
        name: "rainBlendMode",
        label: "Mix blend дождя",
        type: "select",
        defaultValue: DEFAULT_ROOM_SETTINGS.rainBlendMode,
        options: RAIN_MIX_BLEND_OPTIONS,
        hint: "Как дождь смешивается со сценой: через rain-layer на светлой теме и через canvas на тёмной.",
      },
      {
        name: "rainDropColor",
        label: "Цвет капель",
        type: "color",
        defaultValue: DEFAULT_ROOM_SETTINGS.rainDropColor,
        hint: "Цвет тела капель дождя в текущей сессии.",
      },
      {
        name: "rainHighlightColor",
        label: "Цвет блика",
        type: "color",
        defaultValue: DEFAULT_ROOM_SETTINGS.rainHighlightColor,
        hint: "Цвет блика и specular-части дождя в текущей сессии.",
      },
      {
        name: "rainBlurBlendMode",
        label: "Mix blend blur",
        type: "select",
        defaultValue: DEFAULT_ROOM_SETTINGS.rainBlurBlendMode,
        options: RAIN_MIX_BLEND_OPTIONS,
        enabledWhen: { name: "themeMode", values: ["auto", "dark"] },
        hint: "Отдельный режим смешивания CSS blur-подложки на тёмной теме. В фиксированной светлой теме поле отключено.",
      },
      {
        name: "rainBackgroundBlurSteps",
        label: "Blur FX, шаги",
        type: "range",
        min: 0,
        max: 8,
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainBackgroundBlurSteps,
        output: String(DEFAULT_ROOM_SETTINGS.rainBackgroundBlurSteps),
        enabledWhen: { name: "themeMode", values: ["auto", "dark"] },
        hint: "Число шагов размытия background-canvas внутри raindrop-fx на тёмной теме. В фиксированной светлой теме поле отключено.",
      },
      {
        name: "rainBlurPx",
        label: "Blur фона",
        type: "range",
        min: 0,
        max: 40,
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainBlurPx,
        output: `${DEFAULT_ROOM_SETTINGS.rainBlurPx} px`,
        enabledWhen: { name: "themeMode", values: ["auto", "dark"] },
        hint: "Радиус CSS backdrop-filter под дождём на тёмной теме. В фиксированной светлой теме поле отключено.",
      },
      {
        name: "rainBlurOpacity",
        label: "Прозрачность blur",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainBlurOpacity,
        output: `${Math.round(DEFAULT_ROOM_SETTINGS.rainBlurOpacity * 100)}%`,
        enabledWhen: { name: "themeMode", values: ["auto", "dark"] },
        hint: "Видимость нейтральной светлой blur-подложки на тёмной теме. В фиксированной светлой теме поле отключено.",
      },
      {
        name: "rainBlurSaturation",
        label: "Насыщенность blur",
        type: "range",
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainBlurSaturation,
        output: `${Math.round(DEFAULT_ROOM_SETTINGS.rainBlurSaturation * 100)}%`,
        enabledWhen: { name: "themeMode", values: ["auto", "dark"] },
        hint: "Насыщенность фона внутри CSS blur-подложки на тёмной теме. В фиксированной светлой теме поле отключено.",
      },
      {
        name: "rainZIndex",
        label: "Z-index дождя",
        type: "number",
        min: 0,
        max: 30,
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainZIndex,
        output: String(DEFAULT_ROOM_SETTINGS.rainZIndex),
        hint: "Локально меняет высоту слоя дождя. Canvas дождя получает значение на 1 выше, чтобы оставаться поверх слоя.",
      },
      {
        name: "rainEnterEasing",
        label: "Кривая появления",
        type: "cubic-bezier",
        defaultValue: DEFAULT_ROOM_SETTINGS.rainEnterEasing,
        spellCheck: false,
        hint: "CSS timing-function появления слоя дождя. Невалидное значение заменяется стандартной cubic-bezier кривой.",
      },
      {
        name: "rainExitEasing",
        label: "Кривая исчезновения",
        type: "cubic-bezier",
        defaultValue: DEFAULT_ROOM_SETTINGS.rainExitEasing,
        spellCheck: false,
        hint: "CSS timing-function исчезновения слоя дождя. Невалидное значение заменяется стандартной cubic-bezier кривой.",
      },
      {
        name: "rainEnterMs",
        label: "Появление, с",
        type: "range",
        min: 0,
        max: 20,
        step: 0.1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainEnterMs / 1000,
        output: `${(DEFAULT_ROOM_SETTINGS.rainEnterMs / 1000).toFixed(1)} s`,
        hint: "Сколько секунд одновременно проявляется дождь и нарастает громкость его звука.",
      },
      {
        name: "rainExitMs",
        label: "Затухание, с",
        type: "range",
        min: 0,
        max: 20,
        step: 0.1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainExitMs / 1000,
        output: `${(DEFAULT_ROOM_SETTINGS.rainExitMs / 1000).toFixed(1)} s`,
        hint: "Сколько секунд одновременно затухает дождь и стихает его звук.",
      },
    ],
  },
  {
    title: "Капель",
    controls: [
      {
        name: "drizzleEnabled",
        label: "Включить капель",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.drizzleEnabled,
        hint: "Включает или полностью останавливает непрерывный звук капели.",
      },
      {
        name: "drizzleStartVolume",
        label: "Начальная громкость",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.drizzleVolume[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.drizzleVolume[1],
        step: 0.01,
        defaultValue: DEFAULT_ROOM_SETTINGS.drizzleStartVolume,
        output: `${Math.round(DEFAULT_ROOM_SETTINGS.drizzleStartVolume * 100)}%`,
        enabledWhen: "drizzleEnabled",
        hint: "Громкость непрерывной капели, когда камень находится на нижней земле.",
      },
      {
        name: "drizzleEndVolume",
        label: "Конечная громкость",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.drizzleVolume[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.drizzleVolume[1],
        step: 0.01,
        defaultValue: DEFAULT_ROOM_SETTINGS.drizzleEndVolume,
        output: `${Math.round(DEFAULT_ROOM_SETTINGS.drizzleEndVolume * 100)}%`,
        enabledWhen: "drizzleEnabled",
        hint: "Громкость непрерывной капели только в самой верхней точке пути.",
      },
      {
        name: "drizzleVolumeEasing",
        label: "Кривая громкости",
        type: "cubic-bezier",
        defaultValue: DEFAULT_ROOM_SETTINGS.drizzleVolumeEasing,
        enabledWhen: "drizzleEnabled",
        hint: "Кривая изменения громкости по физической высоте камня от нижней земли к вершине.",
      },
    ],
  },
];
