import {
  DEFAULT_ROCK_MAX_WIDTH_VW,
  DEFAULT_ROCK_MIN_WIDTH_VW,
  DEFAULT_ROCK_SCALE_EASING,
  ROCK_WIDTH_VW_LIMITS,
} from "../lib/rockScale.mjs";
import { MIX_BLEND_MODES } from "../lib/settingsModel.mjs";

export const SETTINGS_STORAGE_KEY = "sisyphus-czar-settings-v7";
export const LEGACY_SETTINGS_STORAGE_KEYS = [
  "sisyphus-czar-settings-v6",
  "sisyphus-czar-settings-v5",
  "sisyphus-czar-settings-v3",
  "sisyphus-czar-settings-v2",
];

const MIX_BLEND_LABELS = {
  normal: "Обычное",
  multiply: "Затемнение",
  screen: "Осветление",
  overlay: "Перекрытие",
  darken: "Темнее",
  lighten: "Светлее",
  "color-dodge": "Осветление основы",
  "color-burn": "Затемнение основы",
  "hard-light": "Жёсткий свет",
  "soft-light": "Мягкий свет",
  difference: "Негатив",
  exclusion: "Исключение",
};

const RAIN_MIX_BLEND_OPTIONS = MIX_BLEND_MODES.map((value) => [
  value,
  MIX_BLEND_LABELS[value],
]);

const PHYSICS_FORMULAS = {
  mass: [
    "F_g = m \\cdot g",
    "a_g = \\frac{F_g}{m}",
    "a_{hand} = \\frac{F_{hand}}{m}",
    "v_{release} = v_{pointer} \\cdot a_{hand} \\cdot I \\cdot k",
    "t_{hold} = clamp\\left(\\frac{3000 \\cdot F_{hand}}{5 \\cdot F_g}, 500, 3000\\right)",
    "v_{lift} = clamp\\left(v_0 + k_{lift} \\cdot \\frac{F_{hand}}{F_g}, v_{min}, v_{max}\\right)",
  ],
  gravity: [
    "F_g = m \\cdot g",
    "a_g = \\frac{F_g}{m} = g",
    "F_f = \\mu \\cdot F_g",
    "a_f = \\frac{F_f}{m}",
    "v_y' = v_y + a_g \\cdot \\Delta t",
  ],
  handForce: [
    "a_{hand} = \\frac{F_{hand}}{m}",
    "v_{release} = v_{pointer} \\cdot a_{hand} \\cdot I \\cdot k",
    "t_{hold} = clamp\\left(\\frac{3000 \\cdot F_{hand}}{5 \\cdot F_g}, 500, 3000\\right)",
    "v_{lift} = clamp\\left(v_0 + k_{lift} \\cdot \\frac{F_{hand}}{F_g}, v_{min}, v_{max}\\right)",
  ],
  pointerInfluence: [
    "v_{release} = v_{pointer} \\cdot \\frac{F_{hand}}{m} \\cdot p \\cdot I \\cdot k",
  ],
  bounce: [
    "v_y' = -min(v_y, v_{impactMax}) \\cdot b",
  ],
  inertia: [
    "I = \\frac{inertia}{100}",
    "v_{release} = v_{pointer} \\cdot \\frac{F_{hand}}{m} \\cdot p \\cdot I \\cdot k",
  ],
  groundFriction: [
    "F_f = \\mu \\cdot F_g",
    "a_f = \\frac{F_f}{m}",
    "v_x' = v_x - sign(v_x) \\cdot a_f \\cdot \\Delta t",
  ],
  turbulence: [
    "v_x' = v_x + T \\cdot (sin(5.3t) + 0.6sin(11.7t + 1.3)) \\cdot \\Delta t",
    "v_y' = v_y + 0.35T \\cdot sin(4.1t + 2.6) \\cdot \\Delta t",
  ],
  rockScaleEasing: [
    "h = 1 - \\frac{y}{y_{max}}",
    "s = bezier(h)",
    "w = w_{min} + (w_{max} - w_{min}) \\cdot s",
  ],
  rockMinWidthVw: [
    "w = w_{min} + (w_{max} - w_{min}) \\cdot bezier(h)",
  ],
  rockMaxWidthVw: [
    "w = w_{min} + (w_{max} - w_{min}) \\cdot bezier(h)",
  ],
};

export const SETTINGS_GROUPS = [
  {
    title: "Физика",
    controls: [
      {
        name: "mass",
        label: "Масса",
        type: "range",
        min: 0.1,
        max: 10,
        step: 0.1,
        defaultValue: 1,
        output: "1",
        hint: "Масса камня. Участвует в силе тяжести, ускорении от руки и передаче импульса.",
        formulas: PHYSICS_FORMULAS.mass,
      },
      {
        name: "gravity",
        label: "Тяготение",
        type: "range",
        min: 0.1,
        max: 10,
        step: 0.05,
        defaultValue: 9.8,
        output: "9.80",
        hint: "Ускорение свободного падения g. По умолчанию близко к земному значению 9.8.",
        formulas: PHYSICS_FORMULAS.gravity,
      },
      {
        name: "handForce",
        label: "Сила",
        type: "range",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 50,
        output: "50",
        hint: "Сила руки при броске в шкале от 1 до 100. Больше — камень летит выше и дальше.",
        formulas: PHYSICS_FORMULAS.handForce,
      },
      {
        name: "pointerInfluence",
        label: "Влияние рывка",
        type: "range",
        min: 0,
        max: 2,
        step: 0.1,
        defaultValue: 1,
        output: "1.0",
        hint: "Насколько скорость движения мыши влияет на силу броска. Ноль — рывок не учитывается.",
        formulas: PHYSICS_FORMULAS.pointerInfluence,
      },
      {
        name: "bounce",
        label: "Пружинистость",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.35,
        output: "0.35",
        hint: "Сила пружинистого подпрыгивания камня при ударе о низ. Ноль — камень просто останавливается без отскока.",
        formulas: PHYSICS_FORMULAS.bounce,
      },
      {
        name: "inertia",
        label: "Инерция",
        type: "range",
        min: 0,
        max: 100,
        step: 1,
        defaultValue: 90,
        output: "90",
        hint: "Какую долю скорости движения руки камень получает при отпускании или авто-выпадении. Ноль — без импульса; 100 — максимальная передача с учётом массы, силы и влияния рывка.",
        formulas: PHYSICS_FORMULAS.inertia,
      },
      {
        name: "groundFriction",
        label: "Трение земли",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.35,
        output: "0.35",
        hint: "Сила трения на нижней земле. Больше значение — камень быстрее гасит инерцию после падения на дно.",
        formulas: PHYSICS_FORMULAS.groundFriction,
      },
      {
        name: "turbulence",
        label: "Турбулентность",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.4,
        output: "0.40",
        hint: "Сила воздушной турбулентности при падении: камень покачивается и рыскает в стороны, а не летит по ровной дуге. Ноль — без турбулентности.",
        formulas: PHYSICS_FORMULAS.turbulence,
      },
      {
        name: "rockScaleEasing",
        label: "Кривая размера",
        type: "text",
        defaultValue: DEFAULT_ROCK_SCALE_EASING,
        spellCheck: false,
        hint: "cubic-bezier кривая масштаба камня от нижнего положения к верхнему. Невалидное значение заменяется стандартной кривой.",
        formulas: PHYSICS_FORMULAS.rockScaleEasing,
      },
      {
        name: "rockMinWidthVw",
        label: "Мин. размер, %",
        type: "number",
        min: ROCK_WIDTH_VW_LIMITS[0],
        max: ROCK_WIDTH_VW_LIMITS[1],
        step: 1,
        defaultValue: DEFAULT_ROCK_MIN_WIDTH_VW,
        output: `${DEFAULT_ROCK_MIN_WIDTH_VW}%`,
        hint: "Минимальная ширина камня в процентах от ширины экрана. Высота меняется пропорционально.",
        formulas: PHYSICS_FORMULAS.rockMinWidthVw,
      },
      {
        name: "rockMaxWidthVw",
        label: "Макс. размер, %",
        type: "number",
        min: ROCK_WIDTH_VW_LIMITS[0],
        max: ROCK_WIDTH_VW_LIMITS[1],
        step: 1,
        defaultValue: DEFAULT_ROCK_MAX_WIDTH_VW,
        output: `${DEFAULT_ROCK_MAX_WIDTH_VW}%`,
        hint: "Максимальная ширина камня в процентах от ширины экрана. Высота меняется пропорционально.",
        formulas: PHYSICS_FORMULAS.rockMaxWidthVw,
      },
    ],
  },
  {
    title: "След",
    controls: [
      {
        name: "trailEnabled",
        label: "Показывать след",
        type: "checkbox",
        defaultChecked: false,
        hint: "Включает или выключает отрисовку следа за камнем.",
      },
      {
        name: "lineDelay",
        label: "Задержка",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.5,
        output: "0.50",
        hint: "Насколько плавно и с какой задержкой линия догоняет камень. Ноль — линия точно повторяет путь; больше — линия мягко тянется за камнем с задержкой и сильнее сглаживается.",
      },
      {
        name: "lineWidth",
        label: "Толщина",
        type: "range",
        min: 1,
        max: 60,
        step: 1,
        defaultValue: 6,
        output: "6",
        hint: "Толщина линии следа. Больше значение — толще линия.",
      },
      {
        name: "trailReset",
        label: "Сбрасывать при новом броске",
        type: "checkbox",
        hint: "Стирать след каждый раз, когда камень берут заново. Выключено — след копится.",
      },
      {
        name: "trailMaxPoints",
        label: "Длина следа",
        type: "range",
        min: 20,
        max: 2000,
        step: 10,
        defaultValue: 1000,
        output: "1000",
        hint: "Сколько последних точек пути хранить. Больше — длиннее видимый след.",
      },
      {
        name: "trailUnlimited",
        label: "Без ограничения длины",
        type: "checkbox",
        hint: "Не удалять старые точки следа в этом браузере. При долгой работе расход памяти и нагрузка на отрисовку будут расти.",
      },
      {
        name: "trailSampleDist",
        label: "Частота точек",
        type: "range",
        min: 1,
        max: 40,
        step: 1,
        defaultValue: 6,
        output: "6",
        hint: "Как часто ставится новая точка следа. Меньше значение — точки плотнее и линия глаже.",
      },
    ],
    action: {
      className: "trail-clear",
      label: "Очистить след",
      hint: "Стирает нарисованный след прямо сейчас.",
    },
  },
  {
    title: "Дождь",
    controls: [
      {
        name: "rainEnabled",
        label: "Включить дождь",
        type: "checkbox",
        hint: "Локально включает или выключает дождь по клику. Возврат камня в отпечаток всё равно временно включает ливень.",
      },
      {
        name: "rainStrength",
        label: "Сила дождя",
        type: "range",
        min: 0.25,
        max: 1.5,
        step: 0.05,
        defaultValue: 1,
        output: "100%",
        hint: "Плотность и заметность ливня. Больше значение — больше капель и сильнее дождевой эффект.",
      },
      {
        name: "rainBlendMode",
        label: "Mix blend дождя",
        type: "select",
        defaultValue: "multiply",
        options: RAIN_MIX_BLEND_OPTIONS,
        hint: "Как дождь смешивается со сценой: через rain-layer на светлой теме и через canvas на тёмной.",
      },
      {
        name: "rainBlurBlendMode",
        label: "Mix blend blur",
        type: "select",
        defaultValue: "normal",
        options: RAIN_MIX_BLEND_OPTIONS,
        hint: "Отдельный режим смешивания CSS blur-подложки на тёмной теме.",
      },
      {
        name: "rainBackgroundBlurSteps",
        label: "Blur FX, шаги",
        type: "range",
        min: 0,
        max: 8,
        step: 1,
        defaultValue: 3,
        output: "3",
        hint: "Число шагов размытия background-canvas внутри raindrop-fx на тёмной теме. Изменение перезапускает локальный renderer дождя.",
      },
      {
        name: "rainBlurPx",
        label: "Blur фона",
        type: "range",
        min: 0,
        max: 40,
        step: 1,
        defaultValue: 14,
        output: "14 px",
        hint: "Радиус CSS backdrop-filter под дождём на тёмной теме. Ноль отключает дополнительное размытие фона.",
      },
      {
        name: "rainBlurOpacity",
        label: "Прозрачность blur",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.2,
        output: "20%",
        hint: "Видимость нейтральной светлой blur-подложки на тёмной теме.",
      },
      {
        name: "rainBlurSaturation",
        label: "Насыщенность blur",
        type: "range",
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: 1.1,
        output: "110%",
        hint: "Насыщенность фона внутри CSS blur-подложки на тёмной теме.",
      },
      {
        name: "rainZIndex",
        label: "Z-index дождя",
        type: "number",
        min: 0,
        max: 30,
        step: 1,
        defaultValue: 5,
        output: "5",
        hint: "Локально меняет высоту слоя дождя. Canvas дождя получает значение на 1 выше, чтобы оставаться поверх слоя.",
      },
      {
        name: "rainEnterEasing",
        label: "Кривая появления",
        type: "text",
        defaultValue: "cubic-bezier(0.2, 0, 0, 1)",
        spellCheck: false,
        hint: "CSS timing-function появления слоя дождя. Невалидное значение заменяется стандартной cubic-bezier кривой.",
      },
      {
        name: "rainExitEasing",
        label: "Кривая исчезновения",
        type: "text",
        defaultValue: "cubic-bezier(0.4, 0, 0.2, 1)",
        spellCheck: false,
        hint: "CSS timing-function исчезновения слоя дождя. Невалидное значение заменяется стандартной cubic-bezier кривой.",
      },
      {
        name: "rainEnterMs",
        label: "Появление, мс",
        type: "number",
        min: 0,
        max: 10000,
        step: 50,
        defaultValue: 1100,
        output: "1100",
        hint: "Сколько миллисекунд слой дождя проявляется после включения или возврата камня в отпечаток.",
      },
      {
        name: "rainExitMs",
        label: "Исчезновение, мс",
        type: "number",
        min: 0,
        max: 10000,
        step: 50,
        defaultValue: 2000,
        output: "2000",
        hint: "Сколько миллисекунд слой дождя исчезает после выключения или выхода камня из отпечатка.",
      },
    ],
  },
  {
    title: "След — стиль",
    controls: [
      {
        name: "blendMode",
        label: "Смешивание",
        type: "select",
        defaultValue: "difference",
        options: [
          ["difference", "Негатив"],
          ["normal", "Обычное"],
          ["exclusion", "Исключение"],
          ["screen", "Осветление"],
          ["multiply", "Затемнение"],
        ],
        hint: "Как след накладывается на фон. «Негатив» делает его белым на тёмном фоне и чёрным на светлом.",
      },
      {
        name: "lineColor",
        label: "Цвет линии",
        type: "color",
        defaultValue: "#ffffff",
        hint: "Основной цвет следа. При режиме «Негатив» чистый эффект даёт белый.",
      },
      {
        name: "lineColorTail",
        label: "Цвет хвоста",
        type: "color",
        defaultValue: "#ffffff",
        hint: "Цвет дальнего конца следа. Виден, когда включён градиент.",
      },
      {
        name: "useGradient",
        label: "Градиент к хвосту",
        type: "checkbox",
        hint: "Плавный переход цвета от начала следа к хвосту.",
      },
      {
        name: "lineOpacity",
        label: "Непрозрачность",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.9,
        output: "0.90",
        hint: "Общая видимость линии. Меньше значение — бледнее и прозрачнее.",
      },
      {
        name: "dashStyle",
        label: "Стиль линии",
        type: "select",
        defaultValue: "solid",
        options: [
          ["solid", "Сплошная"],
          ["dashed", "Пунктир"],
          ["dotted", "Точечная"],
        ],
        hint: "Сплошная линия, пунктир или точечный штрих.",
      },
      {
        name: "dashLength",
        label: "Длина штриха",
        type: "range",
        min: 1,
        max: 40,
        step: 1,
        defaultValue: 12,
        output: "12",
        hint: "Длина чёрточки пунктира. Действует для пунктирного стиля.",
      },
      {
        name: "dashGap",
        label: "Промежуток",
        type: "range",
        min: 0,
        max: 40,
        step: 1,
        defaultValue: 8,
        output: "8",
        hint: "Пустое расстояние между чёрточками пунктира.",
      },
      {
        name: "lineCap",
        label: "Концы линии",
        type: "select",
        defaultValue: "round",
        options: [
          ["round", "Скругление"],
          ["butt", "Срез"],
          ["square", "Квадрат"],
        ],
        hint: "Форма кончиков линии: срез, скругление или квадрат.",
      },
      {
        name: "lineJoin",
        label: "Стыки",
        type: "select",
        defaultValue: "round",
        options: [
          ["round", "Скругление"],
          ["miter", "Острые"],
          ["bevel", "Фаска"],
        ],
        hint: "Как выглядят изломы линии на поворотах: острые углы, скругление или срезанная фаска.",
      },
      {
        name: "glow",
        label: "Свечение",
        type: "range",
        min: 0,
        max: 40,
        step: 1,
        defaultValue: 0,
        output: "0",
        hint: "Мягкое размытое сияние вокруг линии. Ноль — без сияния.",
      },
      {
        name: "glowColor",
        label: "Цвет свечения",
        type: "color",
        defaultValue: "#ffffff",
        hint: "Цвет мягкого сияния вокруг линии.",
      },
    ],
  },
];
