import { ROCK_WIDTH_VW_LIMITS } from "../lib/rockScale.mjs";
import { MIX_BLEND_MODES } from "../lib/settingsModel.mjs";
import "../../shared/room-settings.js";

const SharedRoomSettings = globalThis.SisyphusRoomSettings;
const DEFAULT_ROOM_SETTINGS = SharedRoomSettings.DEFAULT_ROOM_SETTINGS;

export const SETTINGS_STORAGE_KEY = "sisyphus-czar-settings-v18";
export const SETTINGS_VERSIONS_STORAGE_KEY = "sisyphus-czar-settings-versions-v1";
export const LEGACY_SETTINGS_STORAGE_KEYS = [
  "sisyphus-czar-settings-v17",
  "sisyphus-czar-settings-v16",
  "sisyphus-czar-settings-v15",
  "sisyphus-czar-settings-v14",
  "sisyphus-czar-settings-v13",
  "sisyphus-czar-settings-v12",
  "sisyphus-czar-settings-v11",
  "sisyphus-czar-settings-v10",
  "sisyphus-czar-settings-v9",
  "sisyphus-czar-settings-v8",
  "sisyphus-czar-settings-v7",
  "sisyphus-czar-settings-v6",
  "sisyphus-czar-settings-v5",
  "sisyphus-czar-settings-v3",
  "sisyphus-czar-settings-v2",
];

const MIX_BLEND_LABELS = {
  normal: "Обычное",
  multiply: "Затемнение",
  screen: "Осветление",
  overlay: "Перекрытие",
  darken: "Темнее",
  lighten: "Светлее",
  "color-dodge": "Осветление основы",
  "color-burn": "Затемнение основы",
  "hard-light": "Жёсткий свет",
  "soft-light": "Мягкий свет",
  difference: "Негатив",
  exclusion: "Исключение",
};

const RAIN_MIX_BLEND_OPTIONS = MIX_BLEND_MODES.map((value) => [
  value,
  MIX_BLEND_LABELS[value],
]);

const PHYSICS_FORMULAS = {
  mass: [
    "F_g = m \\cdot g",
    "a_g = \\frac{F_g}{m}",
    "a_{hand} = \\frac{F_{hand}}{m}",
    "F_{hands} = n \\cdot F_{hand}",
    "F_{surplus} = F_{hands} - F_g",
    "v_{x,release} = v_{x,pointer} \\cdot a_{hand} \\cdot p \\cdot \\frac{I_x}{1000} \\cdot k",
    "v_{y,release} = v_{y,pointer} \\cdot a_{hand} \\cdot p \\cdot \\frac{I_y}{10} \\cdot k",
    "t_{hold} = clamp\\left(\\frac{3000 \\cdot F_{hands}}{5 \\cdot F_g}, 500, 3000\\right)",
    "r = clamp\\left(\\frac{F_{hands}}{F_g}, 0, 1\\right)",
    "v_y = F_{surplus} > 0 ? -v_{lift} : -v_{min} \\cdot bezier(r)",
    "v_{lift} = clamp\\left(v_{min} + k_{lift} \\cdot \\frac{F_{surplus}}{5 \\cdot F_g}, v_{min}, v_{max}\\right)",
  ],
  gravity: [
    "F_g = m \\cdot g",
    "a_g = \\frac{F_g}{m} = g",
    "F_f = \\mu \\cdot F_g",
    "a_f = \\frac{F_f}{m}",
    "v_y' = v_y + a_g \\cdot \\Delta t",
  ],
  handForce: [
    "a_{hand} = \\frac{F_{hand}}{m}",
    "F_{hands} = n \\cdot F_{hand}",
    "F_{surplus} = F_{hands} - F_g",
    "v_{x,release} = v_{x,pointer} \\cdot a_{hand} \\cdot p \\cdot \\frac{I_x}{1000} \\cdot k",
    "v_{y,release} = v_{y,pointer} \\cdot a_{hand} \\cdot p \\cdot \\frac{I_y}{10} \\cdot k",
    "t_{hold} = clamp\\left(\\frac{3000 \\cdot F_{hands}}{5 \\cdot F_g}, 500, 3000\\right)",
    "r = clamp\\left(\\frac{F_{hands}}{F_g}, 0, 1\\right)",
    "v_y = F_{surplus} > 0 ? -v_{lift} : -v_{min} \\cdot bezier(r)",
    "v_{lift} = clamp\\left(v_{min} + k_{lift} \\cdot \\frac{F_{surplus}}{5 \\cdot F_g}, v_{min}, v_{max}\\right)",
  ],
  handForceDeficitEasing: [
    "r = clamp\\left(\\frac{F_{hands}}{F_g}, 0, 1\\right)",
    "k_{deficit} = bezier(r)",
    "v_{deficit} = v_{min} \\cdot k_{deficit}",
  ],
  pointerInfluence: [
    "v_{x,release} = v_{x,pointer} \\cdot \\frac{F_{hand}}{m} \\cdot p \\cdot \\frac{I_x}{1000} \\cdot k",
    "v_{y,release} = v_{y,pointer} \\cdot \\frac{F_{hand}}{m} \\cdot p \\cdot \\frac{I_y}{10} \\cdot k",
  ],
  bounce: [
    "v_y' = -min(v_y, v_{impactMax}) \\cdot b",
  ],
  inertia: [
    "I_y = \\frac{inertia}{10}",
    "v_{y,release}^{up} = v_{y,pointer} \\cdot \\frac{F_{hand}}{m} \\cdot p \\cdot I_y^2 \\cdot k",
    "v_{y,release}^{down} = v_{y,pointer} \\cdot \\frac{F_{hand}}{m} \\cdot p \\cdot I_y \\cdot k",
  ],
  horizontalInertia: [
    "I_x = \\frac{horizontalInertia}{1000}",
    "v_{x,release} = v_{x,pointer} \\cdot \\frac{F_{hand}}{m} \\cdot p \\cdot I_x \\cdot k",
  ],
  groundFriction: [
    "F_f = \\mu \\cdot F_g",
    "a_f = \\frac{F_f}{m} \\cdot k_{scene}",
    "v_x' = v_x - sign(v_x) \\cdot a_f \\cdot \\Delta t",
  ],
  turbulence: [
    "v_x' = v_x + T \\cdot (sin(5.3t) + 0.6sin(11.7t + 1.3)) \\cdot \\Delta t",
  ],
  rockScaleEasing: [
    "h = 1 - \\frac{y}{y_{max}}",
    "s = bezier(h)",
    "w = w_{min} + (w_{max} - w_{min}) \\cdot s",
  ],
  rockMinWidthVw: [
    "w = w_{min} + (w_{max} - w_{min}) \\cdot bezier(h)",
  ],
  rockMaxWidthVw: [
    "w = w_{min} + (w_{max} - w_{min}) \\cdot bezier(h)",
  ],
  sceneHeightScreens: [
    "H_{page} = sceneHeightScreens \\cdot 100vh",
    "k_{scene} = \\frac{100}{sceneHeightScreens} \\cdot 10",
    "a_y' = a_y \\cdot k_{scene}",
  ],
  handWidthVw: [
    "w_{hand} = viewportWidth \\cdot \\frac{handWidthVw}{100}",
  ],
  slaveHandWidthPx: ["w_{slaveHand} = slaveHandWidthPx"],
};

const TRAIL_STYLE_CONTROLS = [
  {
    name: "blendMode",
    label: "Смешивание",
    type: "select",
    defaultValue: DEFAULT_ROOM_SETTINGS.blendMode,
    options: [
      ["difference", "Негатив"],
      ["normal", "Обычное"],
      ["exclusion", "Исключение"],
      ["screen", "Осветление"],
      ["multiply", "Затемнение"],
    ],
    hint: "Как траектория накладывается на фон. «Негатив» делает её белой на тёмном фоне и чёрной на светлом.",
  },
  {
    name: "lineColor",
    label: "Цвет линии",
    type: "color",
    defaultValue: DEFAULT_ROOM_SETTINGS.lineColor,
    hint: "Основной цвет траектории. При режиме «Негатив» чистый эффект даёт белый.",
  },
  {
    name: "lineColorTail",
    label: "Цвет хвоста",
    type: "color",
    defaultValue: DEFAULT_ROOM_SETTINGS.lineColorTail,
    hint: "Цвет дальнего конца траектории. Виден, когда включён градиент.",
  },
  {
    name: "useGradient",
    label: "Градиент к хвосту",
    type: "checkbox",
    defaultChecked: DEFAULT_ROOM_SETTINGS.useGradient,
    hint: "Плавный переход цвета от начала траектории к хвосту.",
  },
  {
    name: "lineOpacity",
    label: "Общая непрозрачность",
    type: "range",
    min: 0,
    max: 1,
    step: 0.05,
    defaultValue: DEFAULT_ROOM_SETTINGS.lineOpacity,
    output: DEFAULT_ROOM_SETTINGS.lineOpacity.toFixed(2),
    hint: "Прозрачность всего слоя траектории после накопления проходов.",
  },
  {
    name: "linePassOpacity",
    label: "Непрозрачность линии",
    type: "range",
    min: 0,
    max: 1,
    step: 0.05,
    defaultValue: DEFAULT_ROOM_SETTINGS.linePassOpacity,
    output: DEFAULT_ROOM_SETTINGS.linePassOpacity.toFixed(2),
    hint: "Вклад одного прохода линии. Повторные проходы по одному месту складываются до полной непрозрачности.",
  },
  {
    name: "dashStyle",
    label: "Стиль линии",
    type: "select",
    defaultValue: DEFAULT_ROOM_SETTINGS.dashStyle,
    options: [
      ["solid", "Сплошная"],
      ["dashed", "Пунктир"],
      ["dotted", "Точечная"],
    ],
    hint: "Сплошная линия, пунктир или точечный штрих.",
  },
  {
    name: "dashLength",
    label: "Длина штриха",
    type: "range",
    min: 1,
    max: 40,
    step: 1,
    defaultValue: DEFAULT_ROOM_SETTINGS.dashLength,
    output: String(DEFAULT_ROOM_SETTINGS.dashLength),
    hint: "Длина чёрточки пунктира. Действует для пунктирного стиля.",
  },
  {
    name: "dashGap",
    label: "Промежуток",
    type: "range",
    min: 0,
    max: 40,
    step: 1,
    defaultValue: DEFAULT_ROOM_SETTINGS.dashGap,
    output: String(DEFAULT_ROOM_SETTINGS.dashGap),
    hint: "Пустое расстояние между чёрточками пунктира.",
  },
  {
    name: "lineCap",
    label: "Концы линии",
    type: "select",
    defaultValue: DEFAULT_ROOM_SETTINGS.lineCap,
    options: [
      ["round", "Скругление"],
      ["butt", "Срез"],
      ["square", "Квадрат"],
    ],
    hint: "Форма кончиков линии: срез, скругление или квадрат.",
  },
  {
    name: "lineJoin",
    label: "Стыки",
    type: "select",
    defaultValue: DEFAULT_ROOM_SETTINGS.lineJoin,
    options: [
      ["round", "Скругление"],
      ["miter", "Острые"],
      ["bevel", "Фаска"],
    ],
    hint: "Как выглядят изломы линии на поворотах: острые углы, скругление или срезанная фаска.",
  },
  {
    name: "glow",
    label: "Свечение",
    type: "range",
    min: 0,
    max: 40,
    step: 1,
    defaultValue: DEFAULT_ROOM_SETTINGS.glow,
    output: String(DEFAULT_ROOM_SETTINGS.glow),
    hint: "Мягкое размытое сияние вокруг линии. Ноль — без сияния.",
  },
  {
    name: "glowColor",
    label: "Цвет свечения",
    type: "color",
    defaultValue: DEFAULT_ROOM_SETTINGS.glowColor,
    hint: "Цвет мягкого сияния вокруг линии.",
  },
];

export function settingsGroupControls(group) {
  return [
    ...(Array.isArray(group.controls) ? group.controls : []),
    ...(Array.isArray(group.subgroups)
      ? group.subgroups.flatMap(settingsGroupControls)
      : []),
  ];
}

export const SETTINGS_GROUPS = [
  {
    title: "Вид",
    controls: [
      {
        name: "themeMode",
        label: "Тема",
        type: "select",
        defaultValue: DEFAULT_ROOM_SETTINGS.themeMode,
        options: [
          ["auto", "Авто"],
          ["dark", "Тёмная"],
          ["light", "Светлая"],
        ],
        hint: "Авто сохраняет текущую механику: светлая тема включается в верхнем отпечатке. Ручные режимы фиксируют выбранную тему локально.",
      },
      {
        name: "sceneHeightScreens",
        label: "Высота страницы",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.sceneHeightScreens[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.sceneHeightScreens[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.sceneHeightScreens,
        output: `${DEFAULT_ROOM_SETTINGS.sceneHeightScreens * 100}vh`,
        hint: "Общая высота сцены в экранах. При изменении автоматически применяется внутренний коэффициент скорости относительно старой длинной сцены 10000vh.",
        formulas: PHYSICS_FORMULAS.sceneHeightScreens,
      },
      {
        name: "returnScrollDurationSeconds",
        label: "Скролл наверх, с",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .returnScrollDurationSeconds[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS
          .returnScrollDurationSeconds[1],
        step: 0.1,
        defaultValue: DEFAULT_ROOM_SETTINGS.returnScrollDurationSeconds,
        output: `${DEFAULT_ROOM_SETTINGS.returnScrollDurationSeconds.toFixed(
          1,
        )} s`,
        hint: "Длительность автоматического скролла страницы к верху при возврате камня в полупрозрачный отпечаток. Ноль — мгновенный переход.",
      },
      {
        name: "returnScrollEasing",
        label: "Кривая скролла",
        type: "text",
        defaultValue: DEFAULT_ROOM_SETTINGS.returnScrollEasing,
        spellCheck: false,
        hint: "cubic-bezier кривая плавности автоматического скролла страницы к верху. Невалидное значение заменяется стандартной кривой.",
      },
    ],
  },
  {
    title: "Физика",
    controls: [
      {
        name: "gravity",
        label: "Тяготение",
        type: "range",
        min: 0.1,
        max: 100,
        step: 0.05,
        defaultValue: 9.8,
        output: "9.80",
        hint: "Ускорение свободного падения g. По умолчанию близко к земному значению 9.8.",
        formulas: PHYSICS_FORMULAS.gravity,
      },
      {
        name: "turbulence",
        label: "Турбулентность",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.4,
        output: "0.40",
        hint: "Сила воздушной турбулентности: камень рыскает в стороны, но вертикальная скорость от турбулентности не меняется. Ноль — без турбулентности.",
        formulas: PHYSICS_FORMULAS.turbulence,
      },
    ],
  },
  {
    title: "Камень",
    controls: [
      {
        name: "mass",
        label: "Масса",
        type: "range",
        min: 0.1,
        max: 100,
        step: 0.1,
        defaultValue: 1,
        output: "1",
        hint: "Масса камня. Участвует в силе тяжести, ускорении от руки и передаче импульса.",
        formulas: PHYSICS_FORMULAS.mass,
      },
      {
        name: "bounce",
        label: "Пружинистость",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.35,
        output: "0.35",
        hint: "Сила пружинистого подпрыгивания камня при ударе о низ. Ноль — камень просто останавливается без отскока.",
        formulas: PHYSICS_FORMULAS.bounce,
      },
      {
        name: "inertia",
        label: "Вертикальная инерция",
        type: "range",
        min: 0,
        max: 1,
        step: 0.01,
        defaultValue: 0.9,
        output: "0.90",
        hint: "Коэффициент вертикального импульса при отпускании или авто-выпадении. В физике значение делится на 10: 1 на ползунке даёт 0.1 реального коэффициента.",
        formulas: PHYSICS_FORMULAS.inertia,
      },
      {
        name: "horizontalInertia",
        label: "Горизонтальная инерция",
        type: "range",
        min: 0,
        max: 1,
        step: 0.01,
        defaultValue: 0.02,
        output: "0.02",
        hint: "Отдельный коэффициент горизонтального импульса. В физике значение делится на 1000, чтобы камень не улетал в стороны.",
        formulas: PHYSICS_FORMULAS.horizontalInertia,
      },
      {
        name: "groundFriction",
        label: "Трение земли",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.35,
        output: "0.35",
        hint: "Сила трения на нижней земле. Больше значение — камень быстрее гасит инерцию после падения на дно.",
        formulas: PHYSICS_FORMULAS.groundFriction,
      },
      {
        name: "rockScaleEasing",
        label: "Кривая размера",
        type: "text",
        defaultValue: DEFAULT_ROOM_SETTINGS.rockScaleEasing,
        spellCheck: false,
        hint: "cubic-bezier кривая масштаба камня от нижнего положения к верхнему. Невалидное значение заменяется стандартной кривой.",
        formulas: PHYSICS_FORMULAS.rockScaleEasing,
      },
      {
        name: "rockMinWidthVw",
        label: "Мин. размер, %",
        type: "number",
        min: ROCK_WIDTH_VW_LIMITS[0],
        max: ROCK_WIDTH_VW_LIMITS[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockMinWidthVw,
        output: `${DEFAULT_ROOM_SETTINGS.rockMinWidthVw}%`,
        hint: "Минимальная ширина камня в процентах от ширины экрана. Высота меняется пропорционально.",
        formulas: PHYSICS_FORMULAS.rockMinWidthVw,
      },
      {
        name: "rockMaxWidthVw",
        label: "Макс. размер, %",
        type: "number",
        min: ROCK_WIDTH_VW_LIMITS[0],
        max: ROCK_WIDTH_VW_LIMITS[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rockMaxWidthVw,
        output: `${DEFAULT_ROOM_SETTINGS.rockMaxWidthVw}%`,
        hint: "Максимальная ширина камня в процентах от ширины экрана. Высота меняется пропорционально.",
        formulas: PHYSICS_FORMULAS.rockMaxWidthVw,
      },
    ],
  },
  {
    title: "Руки",
    controls: [
      {
        name: "handForce",
        label: "Сила",
        type: "range",
        min: 1,
        max: 1000,
        step: 1,
        defaultValue: 50,
        output: "50",
        hint: "Сила одной руки в шкале от 1 до 1000. Руки суммируются: при нехватке силы камень поднимается медленнее, а избыток силы ускоряет подъём.",
        formulas: PHYSICS_FORMULAS.handForce,
      },
      {
        name: "handForceDeficitEasing",
        label: "Кривая нехватки силы",
        type: "text",
        defaultValue: DEFAULT_ROOM_SETTINGS.handForceDeficitEasing,
        spellCheck: false,
        hint: "cubic-bezier кривая замедления подъёма, когда суммарная сила рук меньше силы тяжести. Невалидное значение заменяется последней корректной или стандартной кривой.",
        formulas: PHYSICS_FORMULAS.handForceDeficitEasing,
      },
      {
        name: "pointerInfluence",
        label: "Влияние рывка",
        type: "range",
        min: 0,
        max: 10,
        step: 0.1,
        defaultValue: 1,
        output: "1.0",
        hint: "Насколько скорость движения мыши влияет на силу броска. Ноль — рывок не учитывается.",
        formulas: PHYSICS_FORMULAS.pointerInfluence,
      },
      {
        name: "handWidthVw",
        label: "Размер master-руки, vw",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.handWidthVw[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.handWidthVw[1],
        step: 0.125,
        defaultValue: DEFAULT_ROOM_SETTINGS.handWidthVw,
        output: `${DEFAULT_ROOM_SETTINGS.handWidthVw.toFixed(1)}vw`,
        hint: "Общая ширина большой master-руки в процентах от ширины экрана. Меняется у всех участников комнаты.",
        formulas: PHYSICS_FORMULAS.handWidthVw,
      },
      {
        name: "slaveHandWidthPx",
        label: "Размер slave-руки, px",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.slaveHandWidthPx[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.slaveHandWidthPx[1],
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.slaveHandWidthPx,
        output: `${DEFAULT_ROOM_SETTINGS.slaveHandWidthPx.toFixed(0)}px`,
        hint: "Общая ширина маленькой slave-руки в пикселях. Меняется у всех участников комнаты.",
        formulas: PHYSICS_FORMULAS.slaveHandWidthPx,
      },
    ],
  },
  {
    title: "Траектория",
    controls: [
      {
        name: "trailEnabled",
        label: "Показывать траекторию",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.trailEnabled,
        hint: "Включает или выключает отрисовку траектории за камнем.",
      },
      {
        name: "lineDelay",
        label: "Задержка",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: DEFAULT_ROOM_SETTINGS.lineDelay,
        output: DEFAULT_ROOM_SETTINGS.lineDelay.toFixed(2),
        hint: "Насколько плавно и с какой задержкой линия догоняет камень. Ноль — линия точно повторяет путь; больше — линия мягко тянется за камнем с задержкой и сильнее сглаживается.",
      },
      {
        name: "lineWidth",
        label: "Толщина",
        type: "range",
        min: 1,
        max: 60,
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.lineWidth,
        output: String(DEFAULT_ROOM_SETTINGS.lineWidth),
        hint: "Толщина линии траектории. Больше значение — толще линия.",
      },
      {
        name: "trailReset",
        label: "Сбрасывать при касании земли",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.trailReset,
        hint: "Стирать траекторию каждый раз, когда камень касается нижней земли. Выключено — траектория копится.",
      },
      {
        name: "trailMaxPoints",
        label: "Длина траектории",
        type: "range",
        min: 20,
        max: 2000,
        step: 10,
        defaultValue: DEFAULT_ROOM_SETTINGS.trailMaxPoints,
        output: String(DEFAULT_ROOM_SETTINGS.trailMaxPoints),
        hint: "Сколько последних точек пути хранить. Больше — длиннее видимая траектория.",
      },
      {
        name: "trailUnlimited",
        label: "Без ограничения длины",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.trailUnlimited,
        hint: "Не удалять старые точки траектории в этом браузере. При долгой работе расход памяти и нагрузка на отрисовку будут расти.",
      },
      {
        name: "trailSampleDist",
        label: "Частота точек",
        type: "range",
        min: 1,
        max: 40,
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.trailSampleDist,
        output: String(DEFAULT_ROOM_SETTINGS.trailSampleDist),
        hint: "Как часто ставится новая точка траектории. Меньше значение — точки плотнее и линия глаже.",
      },
    ],
    subgroups: [
      {
        title: "Стиль",
        controls: TRAIL_STYLE_CONTROLS,
      },
    ],
    action: {
      className: "trail-clear",
      label: "Очистить траекторию",
      hint: "Стирает нарисованную траекторию прямо сейчас.",
    },
  },
  {
    title: "Дождь",
    controls: [
      {
        name: "rainEnabled",
        label: "Включить дождь",
        type: "checkbox",
        defaultChecked: DEFAULT_ROOM_SETTINGS.rainEnabled,
        hint: "Локально включает или выключает дождь по клику. Возврат камня в отпечаток всё равно временно включает ливень.",
      },
      {
        name: "rainStrength",
        label: "Сила дождя",
        type: "range",
        min: 0.25,
        max: 1.5,
        step: 0.05,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainStrength,
        output: `${Math.round(DEFAULT_ROOM_SETTINGS.rainStrength * 100)}%`,
        hint: "Плотность и заметность ливня. Больше значение — больше капель и сильнее дождевой эффект.",
      },
      {
        name: "rainMaxVolume",
        label: "Максимальная громкость",
        type: "range",
        min: SharedRoomSettings.ROOM_SETTINGS_LIMITS.rainMaxVolume[0],
        max: SharedRoomSettings.ROOM_SETTINGS_LIMITS.rainMaxVolume[1],
        step: 0.01,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainMaxVolume,
        output: `${Math.round(DEFAULT_ROOM_SETTINGS.rainMaxVolume * 100)}%`,
        hint: "Целевая громкость звука дождя. Значения выше 100% усиливают сигнал через Web Audio.",
      },
      {
        name: "rainBlendMode",
        label: "Mix blend дождя",
        type: "select",
        defaultValue: DEFAULT_ROOM_SETTINGS.rainBlendMode,
        options: RAIN_MIX_BLEND_OPTIONS,
        hint: "Как дождь смешивается со сценой: через rain-layer на светлой теме и через canvas на тёмной.",
      },
      {
        name: "rainDropColor",
        label: "Цвет капель",
        type: "color",
        defaultValue: DEFAULT_ROOM_SETTINGS.rainDropColor,
        hint: "Общий цвет тела капель дождя для всех участников комнаты.",
      },
      {
        name: "rainHighlightColor",
        label: "Цвет блика",
        type: "color",
        defaultValue: DEFAULT_ROOM_SETTINGS.rainHighlightColor,
        hint: "Общий цвет блика и specular-части дождя для всех участников комнаты.",
      },
      {
        name: "rainBlurBlendMode",
        label: "Mix blend blur",
        type: "select",
        defaultValue: DEFAULT_ROOM_SETTINGS.rainBlurBlendMode,
        options: RAIN_MIX_BLEND_OPTIONS,
        hint: "Отдельный режим смешивания CSS blur-подложки на тёмной теме.",
      },
      {
        name: "rainBackgroundBlurSteps",
        label: "Blur FX, шаги",
        type: "range",
        min: 0,
        max: 8,
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainBackgroundBlurSteps,
        output: String(DEFAULT_ROOM_SETTINGS.rainBackgroundBlurSteps),
        hint: "Число шагов размытия background-canvas внутри raindrop-fx на тёмной теме. Изменение перезапускает локальный renderer дождя.",
      },
      {
        name: "rainBlurPx",
        label: "Blur фона",
        type: "range",
        min: 0,
        max: 40,
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainBlurPx,
        output: `${DEFAULT_ROOM_SETTINGS.rainBlurPx} px`,
        hint: "Радиус CSS backdrop-filter под дождём на тёмной теме. Ноль отключает дополнительное размытие фона.",
      },
      {
        name: "rainBlurOpacity",
        label: "Прозрачность blur",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainBlurOpacity,
        output: `${Math.round(DEFAULT_ROOM_SETTINGS.rainBlurOpacity * 100)}%`,
        hint: "Видимость нейтральной светлой blur-подложки на тёмной теме.",
      },
      {
        name: "rainBlurSaturation",
        label: "Насыщенность blur",
        type: "range",
        min: 0,
        max: 2,
        step: 0.05,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainBlurSaturation,
        output: `${Math.round(DEFAULT_ROOM_SETTINGS.rainBlurSaturation * 100)}%`,
        hint: "Насыщенность фона внутри CSS blur-подложки на тёмной теме.",
      },
      {
        name: "rainZIndex",
        label: "Z-index дождя",
        type: "number",
        min: 0,
        max: 30,
        step: 1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainZIndex,
        output: String(DEFAULT_ROOM_SETTINGS.rainZIndex),
        hint: "Локально меняет высоту слоя дождя. Canvas дождя получает значение на 1 выше, чтобы оставаться поверх слоя.",
      },
      {
        name: "rainEnterEasing",
        label: "Кривая появления",
        type: "text",
        defaultValue: DEFAULT_ROOM_SETTINGS.rainEnterEasing,
        spellCheck: false,
        hint: "CSS timing-function появления слоя дождя. Невалидное значение заменяется стандартной cubic-bezier кривой.",
      },
      {
        name: "rainExitEasing",
        label: "Кривая исчезновения",
        type: "text",
        defaultValue: DEFAULT_ROOM_SETTINGS.rainExitEasing,
        spellCheck: false,
        hint: "CSS timing-function исчезновения слоя дождя. Невалидное значение заменяется стандартной cubic-bezier кривой.",
      },
      {
        name: "rainEnterMs",
        label: "Появление, с",
        type: "range",
        min: 0,
        max: 20,
        step: 0.1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainEnterMs / 1000,
        output: `${(DEFAULT_ROOM_SETTINGS.rainEnterMs / 1000).toFixed(1)} s`,
        hint: "Сколько секунд одновременно проявляется дождь и нарастает громкость его звука.",
      },
      {
        name: "rainExitMs",
        label: "Затухание, с",
        type: "range",
        min: 0,
        max: 20,
        step: 0.1,
        defaultValue: DEFAULT_ROOM_SETTINGS.rainExitMs / 1000,
        output: `${(DEFAULT_ROOM_SETTINGS.rainExitMs / 1000).toFixed(1)} s`,
        hint: "Сколько секунд одновременно затухает дождь и стихает его звук.",
      },
    ],
  },
];
