export const SETTINGS_STORAGE_KEY = "sisyphus-czar-settings-v2";

export const SETTINGS_GROUPS = [
  {
    title: "Физика",
    controls: [
      {
        name: "mass",
        label: "Масса",
        type: "range",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 4,
        output: "4",
        hint: "Масса камня. Чем тяжелее — тем медленнее подъём, медленнее разгон и слабее бросок.",
      },
      {
        name: "gravity",
        label: "Тяготение",
        type: "range",
        min: 1,
        max: 10,
        step: 0.1,
        defaultValue: 1,
        output: "1.0",
        hint: "Сила притяжения к земле. Больше значение — камень падает быстрее и медленнее поднимается.",
      },
      {
        name: "handForce",
        label: "Сила",
        type: "range",
        min: 1,
        max: 10,
        step: 1,
        defaultValue: 5,
        output: "5",
        hint: "Сила руки при броске. Больше — камень летит выше и дальше.",
      },
      {
        name: "pointerInfluence",
        label: "Влияние рывка",
        type: "range",
        min: 0,
        max: 2,
        step: 0.1,
        defaultValue: 1,
        output: "1.0",
        hint: "Насколько скорость движения мыши влияет на силу броска. Ноль — рывок не учитывается.",
      },
      {
        name: "bounce",
        label: "Пружинистость",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.35,
        output: "0.35",
        hint: "Сила пружинистого подпрыгивания камня при ударе о низ. Ноль — камень просто останавливается без отскока.",
      },
      {
        name: "inertia",
        label: "Инерция",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.9,
        output: "0.90",
        hint: "Насколько камень сохраняет горизонтальный импульс после броска. Больше — дольше несёт по инерции; меньше — быстрее теряет ход.",
      },
      {
        name: "sliding",
        label: "Скольжение",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.35,
        output: "0.35",
        hint: "Трение пола. Больше значение — камень быстрее тормозит, когда скользит по нижней поверхности.",
      },
      {
        name: "turbulence",
        label: "Турбулентность",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.4,
        output: "0.40",
        hint: "Сила воздушной турбулентности при падении: камень покачивается и рыскает в стороны, а не летит по ровной дуге. Ноль — без турбулентности.",
      },
    ],
  },
  {
    title: "След",
    controls: [
      {
        name: "trailEnabled",
        label: "Показывать след",
        type: "checkbox",
        defaultChecked: true,
        hint: "Включает или выключает отрисовку следа за камнем.",
      },
      {
        name: "lineDelay",
        label: "Задержка",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.5,
        output: "0.50",
        hint: "Насколько плавно и с какой задержкой линия догоняет камень. Ноль — линия точно повторяет путь; больше — линия мягко тянется за камнем с задержкой и сильнее сглаживается.",
      },
      {
        name: "lineWidth",
        label: "Толщина",
        type: "range",
        min: 1,
        max: 60,
        step: 1,
        defaultValue: 6,
        output: "6",
        hint: "Толщина линии следа. Больше значение — толще линия.",
      },
      {
        name: "trailReset",
        label: "Сбрасывать при новом броске",
        type: "checkbox",
        hint: "Стирать след каждый раз, когда камень берут заново. Выключено — след копится.",
      },
      {
        name: "trailMaxPoints",
        label: "Длина следа",
        type: "range",
        min: 20,
        max: 2000,
        step: 10,
        defaultValue: 1000,
        output: "1000",
        hint: "Сколько последних точек пути хранить. Больше — длиннее видимый след.",
      },
      {
        name: "trailUnlimited",
        label: "Без ограничения длины",
        type: "checkbox",
        hint: "Не удалять старые точки следа в этом браузере. При долгой работе расход памяти и нагрузка на отрисовку будут расти.",
      },
      {
        name: "trailSampleDist",
        label: "Частота точек",
        type: "range",
        min: 1,
        max: 40,
        step: 1,
        defaultValue: 6,
        output: "6",
        hint: "Как часто ставится новая точка следа. Меньше значение — точки плотнее и линия глаже.",
      },
    ],
    action: {
      className: "trail-clear",
      label: "Очистить след",
      hint: "Стирает нарисованный след прямо сейчас.",
    },
  },
  {
    title: "Дождь",
    controls: [
      {
        name: "rainStrength",
        label: "Сила дождя",
        type: "range",
        min: 0.25,
        max: 1.5,
        step: 0.05,
        defaultValue: 1,
        output: "100%",
        hint: "Насколько сильным будет ливень при удержании камня в исходном отпечатке.",
      },
      {
        name: "rainEnterEasing",
        label: "Кривая появления",
        type: "text",
        defaultValue: "cubic-bezier(0.2, 0, 0, 1)",
        spellCheck: false,
        hint: "CSS timing-function для появления дождя. Невалидное значение заменяется стандартной cubic-bezier кривой.",
      },
      {
        name: "rainExitEasing",
        label: "Кривая исчезновения",
        type: "text",
        defaultValue: "cubic-bezier(0.4, 0, 0.2, 1)",
        spellCheck: false,
        hint: "CSS timing-function для исчезновения дождя. Невалидное значение заменяется стандартной cubic-bezier кривой.",
      },
      {
        name: "rainEnterMs",
        label: "Появление, мс",
        type: "number",
        min: 0,
        max: 10000,
        step: 50,
        defaultValue: 1100,
        output: "1100",
        hint: "Сколько миллисекунд дождь набирает видимость после возврата камня в отпечаток.",
      },
      {
        name: "rainExitMs",
        label: "Исчезновение, мс",
        type: "number",
        min: 0,
        max: 10000,
        step: 50,
        defaultValue: 2000,
        output: "2000",
        hint: "Сколько миллисекунд дождь плавно исчезает после выхода камня из отпечатка.",
      },
    ],
  },
  {
    title: "След — стиль",
    controls: [
      {
        name: "blendMode",
        label: "Смешивание",
        type: "select",
        defaultValue: "difference",
        options: [
          ["difference", "Негатив"],
          ["normal", "Обычное"],
          ["exclusion", "Исключение"],
          ["screen", "Осветление"],
          ["multiply", "Затемнение"],
        ],
        hint: "Как след накладывается на фон. «Негатив» делает его белым на тёмном фоне и чёрным на светлом.",
      },
      {
        name: "lineColor",
        label: "Цвет линии",
        type: "color",
        defaultValue: "#ffffff",
        hint: "Основной цвет следа. При режиме «Негатив» чистый эффект даёт белый.",
      },
      {
        name: "lineColorTail",
        label: "Цвет хвоста",
        type: "color",
        defaultValue: "#ffffff",
        hint: "Цвет дальнего конца следа. Виден, когда включён градиент.",
      },
      {
        name: "useGradient",
        label: "Градиент к хвосту",
        type: "checkbox",
        hint: "Плавный переход цвета от начала следа к хвосту.",
      },
      {
        name: "lineOpacity",
        label: "Непрозрачность",
        type: "range",
        min: 0,
        max: 1,
        step: 0.05,
        defaultValue: 0.9,
        output: "0.90",
        hint: "Общая видимость линии. Меньше значение — бледнее и прозрачнее.",
      },
      {
        name: "dashStyle",
        label: "Стиль линии",
        type: "select",
        defaultValue: "solid",
        options: [
          ["solid", "Сплошная"],
          ["dashed", "Пунктир"],
          ["dotted", "Точечная"],
        ],
        hint: "Сплошная линия, пунктир или точечный штрих.",
      },
      {
        name: "dashLength",
        label: "Длина штриха",
        type: "range",
        min: 1,
        max: 40,
        step: 1,
        defaultValue: 12,
        output: "12",
        hint: "Длина чёрточки пунктира. Действует для пунктирного стиля.",
      },
      {
        name: "dashGap",
        label: "Промежуток",
        type: "range",
        min: 0,
        max: 40,
        step: 1,
        defaultValue: 8,
        output: "8",
        hint: "Пустое расстояние между чёрточками пунктира.",
      },
      {
        name: "lineCap",
        label: "Концы линии",
        type: "select",
        defaultValue: "round",
        options: [
          ["round", "Скругление"],
          ["butt", "Срез"],
          ["square", "Квадрат"],
        ],
        hint: "Форма кончиков линии: срез, скругление или квадрат.",
      },
      {
        name: "lineJoin",
        label: "Стыки",
        type: "select",
        defaultValue: "round",
        options: [
          ["round", "Скругление"],
          ["miter", "Острые"],
          ["bevel", "Фаска"],
        ],
        hint: "Как выглядят изломы линии на поворотах: острые углы, скругление или срезанная фаска.",
      },
      {
        name: "glow",
        label: "Свечение",
        type: "range",
        min: 0,
        max: 40,
        step: 1,
        defaultValue: 0,
        output: "0",
        hint: "Мягкое размытое сияние вокруг линии. Ноль — без сияния.",
      },
      {
        name: "glowColor",
        label: "Цвет свечения",
        type: "color",
        defaultValue: "#ffffff",
        hint: "Цвет мягкого сияния вокруг линии.",
      },
    ],
  },
];
